chaser.ml
desugarModules.ml
examples/todoDb.links
examples/webserver/examples.links
moduleUtils.ml
moduleUtils.mli
tests/modules.tests
tests/modules/constructor-test-bad.links
tests/modules/constructor-test-good.links
tests/modules/records.links
tests/modules/switch-test.links

Most examples seem to work now!
There is an issue with todoDb -- although the module desugaring pass
seems to do exactly what it's supposed to, a later pass seems to
rearrange the bindings in such a way that the 3 functions aren't treated
as mutually-recursive anymore. This is fixed (seemingly) when the
mutually-recursive "showList" function isn't called directly. More
investigation needed.
The other problem is that Pacman seems to cause a stack overflow.

More testing and fixes to modules

---

CHANGES
INSTALL
INSTALL-OLD

I'll add to this PR with more release-based things...

New installation instructions and changelog

---

examples/handlers/issues/tambug.links
frontend.ml
instantiate.ml
typeSugar.ml

As it turns out this is an issue that has been reintroduced. It was initially resolved back in August 1, 2015 by commenting out FixTypeAbstractions in `frontend.ml`.

Fix issue #132

---

irtojs.ml
irtojs.mli

I have removed dead code from `irtojs.ml` and `irtojs.mli`. I will go ahead and merge this PR myself.

Removal of dead code in the JS compiler

---

evalir.ml
lib.ml
proc.ml
proc.mli
tests/messages.tests

Implement spawnWait on the server

---

links.ml

Try this patch @slindley to see whether it fixes your error messages. It is a quick hack. I have basically removed some exception handlers, relying on the existence of a top-level "catch-them-all" handler. For presentational stuff this fix ought to be adequate, however in the long term I would like to fine-grain the exception handling such that every layer throws and handles a particular set of exceptions. 
Fixes #97

Fixes exception propogation

---

prelude.links

Add makeXml function to create arbitrary XML elements

---

examples/sessions/bookshop-cp.links
examples/sessions/draggable.links
lib/js/jslib.js

Main problem was that PIDs weren't being reset after waking up after blocking on an AP. This was interfering with CP processes running on the client.
Also port some client CP examples to run on the client via the webserver
instead of via CGI mode.

Fix concurrency issue

---

lib/js/jslib.js

haveMail was operating on an incorrect PID. This fixes it (and un-breaks the games...)

Fix haveMail

---

examples/handlers/deep_pipes.links
examples/handlers/shallow_pipes.links

Fixed broken pipes examples (handler examples)

---

prelude.links

Fix Issue #249

---

examples/handlers/deep_pipes.links
examples/handlers/deep_state.links
examples/handlers/exceptions.links
examples/handlers/shallow_state.links
examples/handlers/tests.links
sourceCode.ml
tests/handlers.tests

Included (some) handlers examples in the test suite.
(sneaking in a fix to #276 too)

Towards more robust testing for handlers

---

examples/css/doc.css
examples/index.html

Now with the Links-logo as spinner

Add loading spinner to examples page

---

lib/js/jslib.js

This PR inserts explicit return statements in `jslib.js` to expose opportunities for JavaScript engines to tail call optimise.
Fixes #228.

Tail call optimise jslib

---

.travis.yml
links.ml

Trivial changes to make routine REPL responses go to stdout not stderr.

Fix issue 293

---

links.ml
utility.ml

Fixes #288, I think; objections?

* reverse backticks so that they equal pipe operations

---

core/frontend.ml

Let's add this patch before we release Links.

Only run session exceptions desugaring pass if the setting is enabled.

---

core/basicsettings.ml

Because committing to master makes me want to hurl...

Bump version in basicsettings

---

lib/js/jslib.js

1. Continuation in spawnWait must be _makeCont'ed
2. Typo in getTime
3. spawn definitions should call spawnAt

Fixes to JSLib:

---

core/typeSugar.ml
core/utility.ml
tests/handlers.tests

Fixes a problem in typing of patterns in handler cases, where variant patterns would be prematurely closed.

Allow open variants in handler case patterns

---

core/basicsettings.ml
core/irtojs.ml
core/irtojs.mli
core/json.ml
core/page.ml
core/webserver.ml

Missing page module

---

tests/shredding/config.sample

Update shredding config

---

core/query.ml

Quote table names in queries

---

tests/typecheck_examples.tests

Ensure Mind example is IR-typechecked

---

core/lens/lens_column.mli
core/types.mli

small fix to remove compiler warnings

removed compiler warnings

---

core/parser.mly

The obvious thing works to allow qualified type constructor applications

---

core/desugarInners.ml
core/desugarLAttributes.ml
core/parse.ml
core/parseXml.ml
core/parser.mly
core/sugarConstructors.ml
core/sugarConstructorsIntf.ml
core/sugarTraversals.ml
core/sugarTraversals.mli
core/sugartoir.ml
core/sugartypes.ml
core/transformSugar.ml
core/transformSugar.mli
core/utility.ml
core/xmlParser.mly

Define Binder.with_pos separately from Binder.t

---

core/desugarDatatypes.ml
core/moduleUtils.mli
core/parse.ml
core/parse.mli
core/parseXml.ml
core/scanner.ml
core/scanner.mli

I've taken a stab #515. Repetitions eliminated but I'm still not very good with functors, so critical feedback is welcome.

Eliminate code duplication in parse and xmlParse

---

.travis.yml
Makefile

Update and document the Makefile.

---

core/lib.ml
doc/quick-help.pod
examples/citations.links
examples/games/breakout.links
examples/games/pacman.links
examples/games/tetris.links
examples/handlers/racing-lines.links
examples/handlers/sierpinski-triangle.links
lib/js/jslib.js

Rename clientTime to clientTimeMilliseconds and add clientTime

---

polling.sh

Didn't mean to upload this file during my last PR.

remove accidental upload of polling script

---

install_local_opam2.sh

This commit upgrades the local installation of OPAM to the latest
version 2.0.4. Furthermore, this commits also makes a few changes to
the installation script to make it easier to upgrade OPAM in the
future.

Upgrade to OPAM 2.0.4.

---

links-sqlite3.opam

Fixes the OPAM error and warning for the SQLite3 package.

---

links.opam

Fixes the OPAM warning for links.opam package.

---

azure-pipelines.yml
install_local_opam2.sh
tools/configure-postgresql

This patch extends the Azure Pipelines test matrix to include macOS (version 10.13, I think) in addition to Ubuntu 16.04 LTS.

[Azure Pipelines] Extend the test matrix

---

examples/crop.links

This fixes the draggable cropping frame example (along with setting correct initial position information).

Fix draggable cropping frame example

---

core/backend.ml
core/basicsettings.ml

Revert "Decouple IR type structure simplifications from IR type checking."

---

core/irCheck.ml

Solves #721 
There is a bit of a design question about whether or not we want a design where we rely on certain simplifications having taken place before the IR is type-checked or not. We have no mechanism in place checking that certain settings (e.g., `typecheck_ir`) may only be enabled if another setting is set (`simplify_types`).
Until then, this patch fixes the issue that the IR type-checker was failing unless all `Body` constructors were removed from all types beforehand. In particular, it is not necessary anymore to enable `simplify_types` for the IR type-checker to work.

Improve support for `Body and `Alias in IR type equality checks

---

core/basicsettings.ml
core/chaser.ml
core/desugarModules.ml
core/module_hacks.ml
core/parseSettings.ml
tests/binaryTrees.tests
tests/examples_default.config
tests/examples_effect_sugar.config
tests/examples_session_exceptions.config
tests/handlers.tests
tests/modules.tests

Removes the `-m` and ``modules`` settings, enabling them by default.

Modules by default

---

core/instantiate.ml

Following the discussion in #734, this is a step towards supporting shadowing of type variables better.
Concretely, `instantiate.ml` would previously behave erroneously:
The instantiation [Int / a] on 
``` (forall a. a) -> a```
would result in 
``` (forall a. Int) -> Int```
rather than
``` (forall a. a) -> Int```
because  `instantiate.ml` ignored the fact that `ForAll binds type variables.
The diff looks scarier than it should just because the indentation level of most lines changed, make sure to hide whitespace-only changes.

Support shadowing of type variables in instantiate.ml

---

.travis.yml
azure-pipelines.yml
tests/unit/dune

OUnit seems to have been in rather a lot of flux recently. Hopefully this fixes the most recent CI failures.

Hopefully fix unit tests

---

core/closures.ml

This fixes a bug @jstolarek discovered while working on #774:
Consider the following IR pesudo-code where square brackets denote the `tyvars`:
```
fun[e] (f : \forall e. (Int) -e-> Int) (x : Int) {
fun[] (g : (Int) -e-> Int) (y : Int) {
y
}
g x
}
```
Closure conversion should detect that the inner function uses `e` from the oute function and must be generalized over it when hoisting it. However, the current implementation would only look at the body of `g` as well as its parameter `y` when looking for free type variables that must be generalized. Instead, it should also check the type of g itself, where it would discover `e`.

Handle free type variables in function types during closure conversion

---

azure-pipelines.yml

this is to see what the CI does, don't merge

disable mac os azure CI for now

---

core/compilePatterns.ml
tests/collections.tests

hygienic references to library functions in pattern compilation (fix #24)

---

.github/workflows/default.yml

It seems that `conf-libev` is unused.

Simplify CI configuration

---

core/errors.ml

Follow up on #1001. In order to try to guard for the sort of issue
fixed by #1001 this patch catches `NotFound` inside `Errors.display`
and re-raises it as an `InternalError`.

Raise internal error if `NotFound` is uncaught.

---

examples/handlers/choose.links
examples/handlers/concurrency.links
examples/handlers/nim.links
tests/typecheck_examples.tests

This patch brings a couple of handler examples up-to-date with the latest syntax. It also enables the typechecker tests for these programs.

Tidy handlers examples

---

.github/workflows/default.yml

An attempt to fix the CI failure introduced by changes to the ocaml-setup action.

[CI] Downgrade ocaml-setup version

---

.github/workflows/default.yml

Following https://github.com/ocaml/setup-ocaml/issues/179 lets try
ocaml-setup v2 again.

Upgrade ocaml-setup to v2 again.

---

core/lib.ml
core/value.ml
core/value.mli
examples/filter.links
lib/js/jslib.js
prelude.links
tests/xml.tests

A quick and hopefully not too dirty fix for #1037.  Fixes a couple of other weird things about XML along the way.
Let's see if this passes CI, then we should add a test or two.

[WIP] Fix #1037

---

tests/headless/package-lock.json
tests/headless/package.json

CVE-2021-3807
moderate severity
Vulnerable versions: < 6.0.1
Patched version: 6.0.1
ansi-regex is vulnerable to Inefficient Regular Expression Complexity

Implement suggested security fix for headless testing

---

lib/js/jslib.js

Fixes bug related to ClientSpawnLoc

---

tests/shredding/config.pgsql

Fix shredding config

---

core/lib.ml
examples/TicTacToe-Console.links
examples/handlers/nim-webversion.links
examples/handlers/racing-lines.links
examples/handlers/sierpinski-triangle.links
lib/js/jslib.js
tests/operators.tests

Just a quick search and replace, no attempt has been made to check the changed examples still work yet...

Hand refactor Option -> Maybe, fixing #1116

---

core/webif.ml

This is an attempt to work around #1136 in a principled, but ugly, way.
A shorter fix is possible ([8cee258](https://github.com/links-lang/links/pull/1133/commits/8cee258c0419172e314bda2d4b3fb42a1f315287)) but this approach delays fixing the mismatch between closure variable and environment until the point FunctionPtr is called.  Since we are already looking up the function info there and checking various things, that's no real problem, but I don't like this way of doing things because it delays the point where we make things right to the point where something is about to go wrong, rather than the point where we create the FunctionPtr value representing a server-side call request received from the client.
An approach that is both clean and principled would be nicer, but might take a lot …

Attempted workaround for #1136

---

lens/fun_dep.ml
lens/fun_dep.mli
tests/unit/lens/unitTestsLensFDHelpers.ml

to fix problem noticed in #1165

attempt to make lens test pass/be deterministic
