Makefile
chaser.ml
chaser.mli
desugarModules.ml
frontend.ml
moduleUtils.ml
moduleUtils.mli
sourceCode.ml
test-harness
tests/modules.tests
tests/modules/basic-hide.links
tests/modules/basic-inner-qual-resolution.links
tests/modules/basic-open-fully-qual.links
tests/modules/basic-open-no-shadow.links
tests/modules/basic-open-shadow.links
tests/modules/basic-open.links
tests/modules/basic-partial-qualification-open.links
tests/modules/basic-partial-qualification.links
tests/modules/basic-qual-resolution.links
tests/modules/cyclicA.links
tests/modules/cyclicB.links
tests/modules/cyclicC.links
tests/modules/moduleA.links
tests/modules/moduleB.links
tests/modules/moduleC.links
tests/modules/runmulti
utility.ml

We can now have modules over multiple files.
moduleA.links:
```
open ModuleB
foo()
```
moduleB.links:
```
open ModuleC
fun foo() {
bar()
}
```
moduleC.links:
```
fun bar() {
"hello from c!"
}
```
output: "hello from c!" : String
The way the chaser works is to analyse the files (recursively) to check whether any dependencies cannot be satisfied in the current file. Dependencies (provided they form a DAG, which is enforced) will be topologically sorted when discovered, so there's no need for the user to specify a build order. Once all have been discovered and loaded, they are inlined as \`Module blocks within the root file, and the analysis works exactly the same as for namespace resolution.
Next steps:
* The chaser is still a little dumb, as it only looks in the current working directory …

Multi-file Modules

---

basicsettings.ml
chaser.ml
links.ml
loader.ml
moduleUtils.ml
moduleUtils.mli
test-harness
tests/modules.tests

It's now possible to invoke Links with the --path argument, with paths separated by colons, to specify directories to look for Links files when doing module chasing.
Example:
```
links --path="/some/path:~/some/other/path" test.links
```
will, when performing module chasing, look in:
* current working directory
* /some/path
* ~/some/other/path
This should also fix #58 (which seemed to be caused by inconsistencies in different versions of Python).

Add --path for specifying location to look for files

---

typeSugar.ml
types.ml
types.mli

This is a follow-up on my earlier fix to #43. During discussion between @slindley, @dhil and me we concluded that it is really difficult to come up with a general and simple rule when to hide fresh variables in error messages. It seems that the easiest and safest thing to do is to always display all the variables in error messages.

Always display fresh variables in error messages

---

evalir.ml

This is to do the final bullet point of #76, raising a dynamic error if we attempt to use shredding with a database driver other than postgresql.  
I propose to merge this as soon as the CI tests pass.

dbs other than postgres do not support shredding, so raise an error

---

notfound.ml
settings.ml

This PR enables the use of environment variables in configuration files. E.g. one might have `mylinks.config` containing:
```
cache_directory=$HOME/links/cache
prelude=$HOME/links/prelude.links
```
when loaded using `--config=mylinks.config` switch the `Settings` module will automatically expand the variable `HOME` accordingly. The PR also include minimal error handling -- that is, it prints a helpful message such as
```
failed to expand environment variable 'MY_HOME' in value '$MY_HOME/links/cache' while setting 'cache_directory'.
```
whenever one attempts to expand an undefined environment variable.

Support for using environment variables in Links configuration files

---

links.ml

This was causing the IR to be printed regardless of whether the
"show_compiled_ir" flag was set to true. I'm assuming this is a remnant
of closure conversion debugging, and the same effect can now be achieved
with show_compiled_ir?

Remove stray debug statement

---

evalir.ml

Before, a separate continuation frame was created to pass the session
channel when blocking in the evaluation of request / accept in
evalir.ml (according to @slindley, likely an artefact of copying the
pattern employed by the "recv" function).
This patch changes this, so that the value is returned directly,
avoiding creating the intermediate data structure.

Avoid creating cont. frame in request / accept

---

Makefile
evalir.ml
json.ml
jsonparse.mly
proc.ml
proc.mli
processTypes.ml
processTypes.mli
value.ml
value.mli

This commit abstracts away from the current representation of names.
Instead of treating everything as integers, we now have:
* ProcessID
* ChannelID
* AccessPointID
* (ClientID -- unused in this commit)
This helps with distribution, and is the first phase of merging
everything in.

Phase 1: Abstract names

---

webserver.ml

Addresses #151 
Also, for giggles, provides sensible default behavior in response to directory requests along static routes.

Store routing table as a tree; use nearest matching handler to route

---

.travis.yml
Makefile
basicsettings.ml
links.ml
tests/records.tests
tests/tuples.tests
value.ml
value.mli

This replaces string_of_value by a custom formatter which ignores
newlines and indentation.
Pretty printing is always disabled in web_mode.
Pretty printing is always enabled in the REPL.
Pretty printing is disabled by default for file/expression input but
can be enabled by setting print_pretty.
Colors are disabled by default, but can be enabled by setting
print_colors. We only print colors when pretty printing.

Pretty print values -- updated -- 4th try

---

.travis.yml

I forgot to update the opam file with dependencies. That should not happen. This would avoid the issue entirely and we only need to maintain one list of dependencies. Let's see whether that works...

Use deps from opam file for CI build

---

lib/js/jslib.js

- Remove the debug popup
- Replace debug, print, and dump implementations to use `console`
- Add `show` implementation

Improve JavaScript printing

---

lib/js/jslib.js

This is useful for two reasons. Firstly, window.event isn't supported in
Firefox, so this should add support back for some applications.
Secondly, this should fix errors with "getTime" trying to access an
undefined event, for some reason.

Explicit "event" variable in jslib

---

json.ml
value.ml

As per #206, floats can be incorrectly boxed as integers upon deserialisation from JSON. 
This patch adds an ``` `Int ``` case in `value.ml`'s `unbox_float` which rectifies this, and should be a cheap way to fix the issue.

Add int case for float unboxing (Fix #206)

---

examples/distribution/chatserver/chatServer.links
examples/distribution/clientProcessOnServer.links
examples/distribution/clientProcessOnServer2.links
examples/distribution/clientToClient.links
examples/distribution/clientToClientDeleg.links
examples/distribution/clientToServerDeleg.links
examples/distribution/serverToClient.links
examples/distribution/serverToClient2.links
examples/distribution/simpleServerAP.links
examples/sessions/bookshop-cp.links
examples/sessions/bookshopAppServer.links
examples/sessions/draggable.links
examples/webserver/draggable.links
examples/webserver/examples-nodb.links
examples/webserver/examples.links
examples/webserver/progress.links
examples/webserver/wsocket_conn.links
prelude.links

As per the discussion in issue #199, revises addRoute to take a single parameter again.
Adds:
- addRoute : (String, (String) ~> Page) ~> ()
- addSimpleRouteHandler : (String, (String) ~> Page) ~> ()
- addLocatedRouteHandler : (String, (String, Location) ~> Page) ~> ()
addRoute and addSimpleRouteHandler have the same behaviour.
addLocatedRouteHandler allows the page render function to be passed an
explicit location, for use in things like spawnAt.

Made addRoute take a single parameter again (Fix #199)

---

evalir.ml
lib.ml
prelude.links
webserver.ml
webserver_types.ml
webserver_types.mli

Adds an error hander per route, called should the route throw an `EvaluationError` or `Wrong` exception, and updates the existing route adding functions to use a default error handler, providing an informative error message.

Add explicit error handling for routes.

---

pg_database.ml

This patch applies `String.escaped` to the given input string and passes the result to the postgres escape_string. `String.escaped` escape any character outside of the ASCII printable range [32-126].
Prior to this patch the postgres driver would blow up when given a non-ASCII string such as yours truly surname.
I have created this PR for informative purposes. I'll self-approve this PR, since the change is minor and needed immediately.

Hotfix postgres escape_string to work with non-ASCII characters.

---

basicsettings.ml
moduleUtils.ml
opam
stdlib/binaryTree.links
stdlib/comparators.links
tests/binaryTrees.tests
tests/stdlibtests/binaryTree/inorder.links
tests/stdlibtests/binaryTree/postorder.links
tests/stdlibtests/binaryTree/preorder.links
tests/stdlibtests/binaryTree/remove1.links
tests/stdlibtests/binaryTree/remove2.links

All this essentially does is adds a distinguished directory which is (by
default) included in the module path. The key idea is that we should be
able to import things from the standard library when we need them,
rather than having things in the prelude which are there all the time.
(also, have a basic binary tree library as a freebie...)

Add ability to have a "standard library"

---

json.ml
jsonparse.mly
lib/js/jslib.js
resolveJsonState.ml
value.ml
value.mli

This assigns a unique reference to serialised DOM nodes and stores them in
a dictionary, allowing them to be serialised and deserialised correctly.
This should fix #207.

Emulate DOM reference serialisation (fix #207)

---

opam

It's not playing nicely with 4.1 at the moment, so constraining for now.

Constrain Postgres bindings to 4.0.1.

---

Makefile
Makefile.sample.config
opam

Turns out we were trying to recompile the OPAM-installed version of postgresql. I still don't know why it started breaking now, but we shouldn't do that. See here for the full story: https://github.com/mmottl/postgresql-ocaml/issues/21
This PR assumes that we will only ever use the OPAM-installed version. This way we can use the regular mechanism for linking with OPAM-installed dependencies. We don't require the whole CLIBS, EXTRA_LIBDIR, and stuff anymore, I think.
I only tested the postgresql backend.
Someone who knows anything about Makefiles should check whether this makes sense.
Anyone who cares about MySQL/SQLite should check them.

Fix mysterious postgresql 4.1.0 build failure

---

examples/css/doc.css
examples/index.html

Design things

---

irtojs.ml

We need to ensure that makeCont is called instead of passing a
direct-style contination.
This fixes chatserver and bookstore.

Fix client-side compilation of session choice

---

examples/handlers/shallowstate.links
value.ml

* Fixed bug in the dynamic semantics for shallow handlers
* ... consequently, I *unimplemented* a few cases until I have decided what the intended (if any) semantics are.
* Fixed previously broken shallow state example.
* Added basic debug module for debugging handlers.

Fixed bug in shallow handlers dynamics

---

examples/css/doc.css
examples/index.html

- When viewing on desktop, history is updated for the currently viewed example
- Loading an URL with query parameters loads the example in the frame
- On mobile it redirects to the example page

Add history manipulation to the examples page

---

run-tests

In theory we could connect to a remote host, but there does not seem to
be a way to provide a password to psql, so maybe not that useful...
This closes #250.

Use port from config to prepare database for tests

---

Makefile
lib.ml
opam
tests/crypt.tests

Whenever there is a login or something to build, password really shouldn't end up in the DB in plain text !
This PR adds
Please especially check whether there are changes missing for the added dependency.
(Also: What is the correct OCaml way to get rid of the warning `implicit elimination of optional arguments ?count, ?seed` ?)

Add crypt hash and verification functions

---

examples/games/pacman.links
examples/games/tetris.links
irtojs.ml
json.ml
json.mli
jsonparse.mly
lib.ml
lib/js/jslib.js

One thing I'm not terribly happy about is the fact that I currently represent Nil as [] (i.e., the empty Javascript Array). This is mostly due to the fact that it's short and easy to parse. If we used something different, like a dedicated string or the empty object {}, it would be kind of hacky to parse this to the empty list in jsonparse.mly.
In addition, I could have squashed a few commits. In particular, what I did in 
bed80f3 was later mostly reverted. Do we pay a lot of attentition to squashing such useless commits?

Fixed Issue 35 (use linked lists in JS)

---

instantiate.ml
types.ml
types.mli

Pick a low-hanging error message "fruit". We could always do better,
but this should be enough to finally close #19 which was reported
almost 3 years ago.

Better error message for kind error during type alias application

---

Makefile

Shamelessly nicked from Mirage, these Makefile rules make it possible to release multiple packages at once. I'll update the wiki with details of how to use these.

Add opam multi-package rules to makefile

---

core/evalir.ml
core/irtojs.ml
core/json.ml
core/json.mli
core/proc.ml
core/proc.mli
core/resolveJsonState.ml
core/resolveJsonState.mli
core/webif.ml
lib/js/jslib.js

This patch inspects all channels sent to the client, includes the buffers in the initial JSON dump, and updates the client locations.
This should fix #323.

Ensure channels created on server are correctly sent to client (Fix #323)

---

examples/draggableDb.links

Previously, the draggable list (database version) example should fetch items in descending order from database which would cause load after save to be effectful, i.e. seemingly reorder all the items in the display. Now the items are fetched in ascending order such that load after save appears is idempotent.
Coincidentally #295 appears to be have fixed. I am unable to reproduce the issue with the current master. 
Resolves #295

Fixes draggable list (database version) example

---

examples/handlers/sat.links
examples/handlers/tests.links

Minor addition to the effect handlers application. This patch adds a SAT-solver program which makes use of a non-deterministic choice operation and an exception operation to determine whether a given boolean expression (with variables) is satisfiable. The same operations are used to implement parsing of the boolean expression language.

SAT solver example (also a new test harness case)

---

core/errors.ml
core/notfound.ml
core/utility.ml

This PR resolves #341.
TL;DR The problem was a combination of two things
1. On line 116 in `errors.ml` we always ran `Printexc.print_backtrace stderr`
2. Some recent version of OCaml has changed the behaviour of `Printexc.print_backtrace` such that it prints the stack trace if available regardless of `OCAMLRUNPARAM` or `CAMLRUNPARAM` being unset.

Resolves issue #341 "No way to disable OCaml stack traces when Links fails"

---

core/typeSugar.ml

This patch makes error message generation more lazy. What works:
* `fun_apply` griper is called only once when reporting incorrect function type. Thus error message is only generated once, when we know it will be displayed to the user
What doesn't:
* if I comment out first two lines of `build_tyvar_names` in `types.ml`, which are the lines responsible for resetting variable name counter, I can easily see that some variable names are being generated even though they are not displayed to the user. This can be witnessed by variable names in error message starting from letters like `k` and not `a`. Is this expected behaviour? Are we generating some variable names for internal use only? If not, then this patch requires further work to determine why this happens. I suspect this might be taking …

More lazy unification errors

---

core/lib.ml
lib/js/jslib.js

Changed the return type of `domSetAttributeFromRef`, `domSetPropertyFromRef` and `domSetStyleAttrFromRef` to unit and adapted the type signatures. 
Related to #354

Fixing #354: Wrong type signatures or implementations for built-in DOM functions

---

core/typeSugar.ml
tests/annotations.tests

Fixes issue #360. 
I picture two potential fixes, either return `t` as in the case for `Var` or unroll the recursive type once, and keep track of the recursive variables already encountered to prevent non-termination. I opted for the latter approach, which may prove be a somewhat conservative option as I have been unable to produce an example that requires unrolling.

Resolves links-lang/links#360

---

lib/js/jslib.js

Fixes minor issue in `domGetChildrenByRef` and `getAttributes`. Instead of returning arrays, resulting in an undefined object, these return linked lists.

Returns linked list instead of arrays

---

core/basicsettings.ml
core/irtojs.ml
core/irtojs.mli
core/json.ml
core/webserver.ml

This PR separates page generation and ir-to-js compilation. Currently, the separation is somewhat crude, this will be rectified by a few upcoming PRs. This PR is one step towards resolving #229.
This PR deprecates the `js_pretty_print` option (one of my next PRs will replace the current JS code generator / pretty printer).

Crude separation of page generation and javascript compilation

---

core/dune

The introduction of shift/reduce conflicts is now regarded as a build error.
Following Jeremy Yallop's suggestion I have added the `--strict' flag
to `ocamlyacc`. We might want to do the same for the other two
parsers.

Make shift/reduce conflicts build time errors

---

core/channelVarUtils.ml
core/closures.ml
core/evalir.ml
core/instantiate.ml
core/instantiate.mli
core/ir.ml
core/ir.mli
core/irTraversals.ml
core/irTraversals.mli
core/irtojs.ml
core/query.ml
core/queryshredding.ml
core/typeUtils.ml
core/typeUtils.mli
core/types.ml
core/types.mli
core/utility.ml
tests/functions.tests
tests/functions/nested-functions-polymorphic.links

I've adapted closures.ml such that not only free term variables are collected, but also free type variables occuring in functions. We then generalize the function over those free variables that are actually bound further up in the AST.
To make this type-check, I've changed the `Closure (f, v) constructor in IR values to  `Closure (f, targs, v), now carrying a list of type arguments. This means that `Closure now has a built-in type application. We cannot just enclose TApp (f, targs) in `Closure instead for the following reasons: 
- f is a variable, not a value. It is important to keep it that way, because the function f must be looked up in a map telling us the type of the closure environment it needs. In particular, the value `Variable f would not type-check to prevent using functions …

Fixed closure conversion to generalize functions over their free type variables when hoisting

---

core/basicsettings.ml

The current behaviour of 'typecheck_only' setting is pointless in the REPL, since turning on the setting and subsequently typing in an expression causes the REPL to quit.

Makes 'typecheck_only' a system setting 

---

test-harness

This fairly straightforward patch updates the test harness to Python 3, removing our dependency on the outdated and soon-to-be-unsupported Python 2.

Update test harness to Python 3 (Fix #409)

---

core/desugarAlienBlocks.ml
core/desugarCP.ml
core/desugarDbs.ml
core/desugarFormlets.ml
core/desugarFors.ml
core/desugarFuns.ml
core/desugarHandlers.ml
core/desugarLAttributes.ml
core/desugarPages.ml
core/desugarProcesses.ml
core/desugarRegexes.ml
core/desugarSessionExceptions.ml
core/parser.mly
core/sugarConstructors.ml
core/sugarConstructors.mli
core/sugarConstructorsIntf.ml
core/sugartypes.ml

This is a refactoring of desugar* modules in an attempt to cut down on clutter by using smart constructors. It addresses #421 and #423. 
For example, code that previously looked like this:
```OCaml
with_pos (`FnAppl
(with_pos (`TAppl (with_pos (`Var "plugP") pos, [`Row (o#lookup_effects)])) pos,
[with_pos (`FunLit
(Some ([Types.make_tuple_type [Types.xml_type], o#lookup_effects]),
`Unl,
([[with_pos (`Variable (make_binder x Types.xml_type pos)) pos]],
with_pos (`Xml (name, attrs, dynattrs,
[with_pos (`Block ([], with_pos (`Var x) pos)) pos])) pos), `Unknown)) pos;
desugar_nodes pos children])) pos
```
now looks like this:
```OCaml
fn_appl "plugP" [`Row (o#lookup_effects)]
[fun_lit ~args:[Types.make_tuple_type [Types.xml_type], o#lookup_effects]
`Unl [[variable_pat ~ty:Types.xml_type x]] …
```

Use smart constructors in desugar* modules

---

core/parser.mly
tests/modules.tests
tests/modules/qualified-type-names.links

This is an attempt to fix #225 while allowing reuse of `.` for session types and qualified types.  It is hacky and wrong, but passes all of the existing tests.
Explanation:
1. Create `primary_datatype_loc` nonterminal for primary_datatypes annotated with their location (so that their semantic actions have the same type as `datatype`)
2. Remove `qualified_type_name` from `parenthesized_datatypes` and make a new nonterminal `qualified_or_primary_datatype` that allows either a non-parenthesized `primary_datatype` or a `qualified_or_primary_datatype`.
3. Move `TILDE datatype` from `session_type` to `primary_datatype` and restrict the second component to be `primary_datatype_loc`. 
The third change was the one I was least pleased about but seems necessary to parse existing type expressions …

[WIP]: hacky fix to issue225

---

tools/rule-check
tools/rules/trailing_whitespace

This PR only checks textual files defined in a whitelist, as opposed to all files except PDFs, for trailing whitespace.
Note that due to syntactically-significant trailing whitespace in Markdown files (as identified by @dhil),`md` files are excluded from this check.
Also, I toyed with the idea of storing the whitelist in an array, but decided against this as it wasn't pleasant to programmatically build up the `find` command, and the alternative was to run the `find` command `m * n` times, where `m` is the number of directories and `n` is the number of extensions.

Whitelist for whitespace check (Fixes #464)

---

core/lexer.mll
tests/xml.tests
tests/xml_comment_newlines.links

Implements something like https://www.w3.org/TR/REC-xml/#sec-comments. It is debatable whether we want to ignore XML comment or reify them as XML nodes. In this patch I have opted for the former. I believe with little extra effort we could implement the latter.
Fixes #270.

Adds support for XML comments. Resolves #270.

---

core/irtojs.ml

This debug output is useless and large, and is a relic from when I was debugging session exceptions. While the `to_string` function is useful for debugging frames, the debug output should never have made it into master. This simple patch removes it, so we have some semblance of useful debug output again.

Stop printing frames in debug output

---

Makefile
bin/dune
core/lexer.mll
core/performance.ml
core/xmlLexer.mll
dune

This PR includes the following changes.
* The release profile treats (most) warnings as errors.
* The build rule \`nc-release' *explicitly* instructs \`dune' to use
the release profile.
* Both build profiles include flags, which disallow some legacy OCaml
features such deprecated modifiers in the Format language. The
profiles also enforces strict sequences, which means that the left
hand side of a sequence must have type \`unit'. The lexers have been
updated to adhere to the strict sequence rule.
* Removes \`-cclib -lunix' and \`-thread' flags from the common build
profile flags, as those are implied by \`core/dune' and \`bin/dune'
respectively.
* The release profile applies -O3 optimisations to the resulting
executable. In the future, we may want to explore the optimisation
space to …

Updates the development and release build profiles.

---

core/page.ml

Did you know that not having a `doctype` on a page can cause subtle CSS bugs? Neither did I, until I spent an hour and a half trying to work out why on earth my CSS was displaying differently despite the class structure being exactly the same!

Add <!doctype html> to each page

---

core/desugarLAttributes.ml
core/parse.ml
core/parseXml.ml
core/parser.mly
core/sugarConstructors.ml
core/sugarConstructorsIntf.ml
core/sugartoir.ml
core/sugartypes.ml
core/utility.ml
core/xmlParser.mly

This patch moves XML node validation from Sugar->Ir stage into the desugaring stage. It also ensures that smart constructor performs the same validation.
Fixes #511

Validate XML nodes during desugaring

---

core/ir.ml
core/value.ml
links.opam

Janek realized that we don't need to suppress warning 39 (about unused rec flags) anymore (see 381fdee26314cc4ae). The warning originated from code generated by earlier versions of ppx_deriving_yojson. Since version 3.3, the generated code doesn't seem to yield those warnings any more. I've therefore un-suppressed those warnings in two additional files.
I'm creating this PR because I'm unsure how we deal with versioning of our dependencies. After my and Janek's change, building a release version of links (or installing a potential future release via opam) would error if one has a pre-3.3 version of ppx_deriving_yojson installed. I therefore added a version constraint to our opam file. Or do we generally give up on tracking the exact version requirements of our dependencies and just hope …

Require recent ppx_deriving_yojson version?

---

core/basicsettings.ml
core/errors.ml
core/frontend.ml
core/sourceCode.ml

This PR addresses two printing related things that frequently annoy me while debugging:
**Dumping ASTs**
I often find myself in a position where I would like to see the sugar AST for a program and hacking something into `frontend.ml` to achieve this.
I've introduced the two settings `show_pre_frontend_sugar_ast` and `show_post_frontend_sugar_ast`. I've switched on, the program AST will be dumped right before, resp. after, executing the frontend pipeline in `frontend.ml`.
**Annoying `pos` fields**
Dumping sugar ASTs (e.g., using Sugartypes.show_program) currently yields a lot of ugly output of the following form:
```
{ SourceCode.WithPos.node =
(Sugartypes.Block
([],
{ SourceCode.WithPos.node =
(Sugartypes.FnAppl (
{ SourceCode.WithPos.node =
(Sugartypes.Var "f"); pos = ... },
[{ …
```

Saner printing of sugar ASTs; settings for dumping ASTs before and after frontend pipeline

---

core/checkXmlQuasiquotes.ml
core/desugarFormlets.ml
core/desugarLAttributes.ml
core/desugarPages.ml
core/desugarRegexes.ml
core/errors.ml
core/errors.mli
core/sugarConstructors.ml

The result of two train-rides' work refactoring how we do error messages in the frontend.
This firstly fixes #531 by removing the logic duplication in formatting HTML -- in turn, this should make it less painful to add new errors (and encourage people to do that, instead of using `failwith`).
This secondly addresses #514 by renaming the confusingly-named `SugarError` to `DesugaringError` and attaching a variant describing a stage to it. In doing this, two things came up:
1. In some places, `SugarError` was used where an `InternalError` was more appropriate
2. In `desugarLAttributes`, dummy positions were used, so I've refactored it to use proper position information now
There are also some other minor refactorings to make things nicer.

Some error message easy wins

---

run-tests

I often find myself accidentally running the wrong set of links tests, and end up having to mash Ctrl+C until all the tests have been killed. This patch causes the first CTRL+C to kill the script as well.

Add tests CTRL+C trap

---

core/errors.ml
core/errors.mli
core/irCheck.ml
core/typeUtils.ml

This is just a cleanup of the error handling in the IR type-checker. In particular, there should be a nicer separation between error handling done inside of the type-checker and the handling done outside of it.
Most of the changes are just because I got rid of some polymorphic variants.
Fixes #539 (together with  3062b583627b3ba750bed5e426593ab33b43ecff).

Nicer IR type-checking error reporting

---

core/irtojs.ml

This was some more debug information used when implementing session exceptions that shouldn't have made it into the main branch, and thus clutters our debug output.

Remove some additional useless debug information

---

core/json.ml

Carriage returns ("\r") were not being correctly escaped, leading to runtime errors.
I tried using `String.escaped` (as with `irtojs`), but some intricacies seemed to be getting in the way there (I think `String.escaped` was doing more than we wanted it to / was safe to do).

Escape carriage returns in JSON-quoted strings

---

core/desugarFormlets.ml
core/sugarConstructors.ml
core/sugarConstructorsIntf.ml

The "smart" constructor `tuple' has a rather hacky method for
preserving 1-tuples, which is not always correct. In particular, it
introduced a soundness regression for formlets.
This commit augments the interface of `tuple' with an optional boolean
flag to enable or disable the said hack. By default the hack is on.
Resolves #576.

Resolves issue #576

---

core/lib.ml
prelude.links
tests/page.tests

This patch refines the type of `unsafeAddRoute`, and its relatives, in
particular `addRoute`, which previously had the type
addRoute : (String, (String) ~> Page) ~> ()
which elaborates to
addRoute : (String, (String) ~e~> Page) ~f~> ()
where `e` and `f` are distinct effect variables. Consequently the
invariant that all user-definable effectful operations are handled
prior to reaching the toplevel is broken, for instance
addRoute("/", fun(_) {do Fail})
would cause a "no handler installed for Fail" error to occur at
runtime when visiting the root page, even though one might have
wrapped the `addRoute` in a handler, i.e.
handle(addRoute("/", fun(_) {do Fail})) {
case Fail -> ()
}
This does not handle the effects of the anonymous function, because the function
gets executed in a separate …

Sound types for the `addRoute'-family of functions.

---

core/desugarFuns.ml
core/transformSugar.ml
tests/empty_prelude.links
tests/typed_ir.tests
tests/typed_ir.tests.config

This is a speculative fix for some of the IR typing problems reported in #446. Namely, this patch fixes unbound type variable errors for anonymous functions. These two examples now compile without IR errors:
```
fun (x) {x};
fun (x) {1};
```
Moreover, compilation of anonymous composition function `fun (f,g) {fun (x){f (g(x))}};` no longer generates these errors but still has some other errors.
The idea behind a fix is that if we see an anonymous function wrapped in a type abstraction we generate a corresponding type application. So previously we would generate:
```
TAbs Y. { 
fun freshfun(x:Z) {x}
freshfun
} 
```
whereas now we generate:
```
TAbs Y. { 
fun freshfun(x:Z) {x}
TApp freshfun [Y]
}
```
There is some voodoo coding here, so please review carefully. If this fix is correct then I …

Generate type applications for desugared anonymous functions

---

core/chaser.ml
core/desugarModules.ml
core/lexer.mll
core/moduleUtils.ml
core/parser.mly
core/sugarConstructors.ml
core/sugarConstructorsIntf.ml
core/sugarTraversals.ml
core/sugartoir.ml
core/sugartypes.ml
core/transformSugar.ml
core/typeSugar.ml

This patch is a step towards the implementation of #571.
This patch introduces the syntax for imports, at the moment they are operationally equivalent to opens, however, that will change in a subsequent patch.

Introduce syntax for imports

---

core/chaser.ml
core/desugarModules.ml
core/parser.mly
core/sugarConstructors.ml
core/sugarConstructorsIntf.ml
core/sugarTraversals.ml
core/sugartypes.ml
examples/handlers/tests.links
examples/sessions/chatserver/chatClient.links
examples/sessions/chatserver/chatServer.links
examples/sessions/mind/mindClient.links
examples/sessions/mind/mindServer.links
examples/webserver/examples-nodb.links
examples/webserver/examples.links
links-mode.el

This patch changes the examples such that they use `import` rather than `open` to require external modules. Currently, `open` subsumes `import`, but not vice versa. In a subsequent patch I will change the semantics of `open` such that it can no longer be used to require an external module.

Switch examples to use import

---

core/desugarModules.ml
tests/modules.tests
tests/modules/open_is_not_include0.links
tests/modules/open_is_not_include1.links
tests/modules/open_is_not_include2.links

The desugar modules patch inadvertently changed the semantics of
`open` to be that of `include`. This regression was spotted by
@SimonJF in #606. From reading the generated code I mistakenly
concluded that it was a loader problem. However, as pointed out by
@SimonJF, the chaser is supposed to lift dependencies into "synthetic"
modules in the combined program.
With that in mind, it became clear to that the desugar modules patch
inadvertently changed the semantics of `open`, because I heedlessly
added the bindings resulting from an `open` to the module scope that
was being built. As a result they would correctly shadow the current
bindings in scope, but they would also inadvertently become part of
the module.
This patch rectifies this mistake. The implementation still makes use
of two-level …

Semantics of `open` is not `include`.

---

bin/repl.ml
core/basicsettings.ml
core/desugarModules.ml

The REPL directive `@load` loads a source file and pulls its contents
into the current scope. If the source file defines any modules the
user cannot access them following a load, because the state of module
desugarer is not preserved between `@load` directives when in
interactive mode.
This patch rectifies this issue such that the state is preserved
between subsequent invocations of the module desugarer. The state is
only preserved when Links is operating is interactive mode.
Depends on #609.

Improve the REPL efficacy when using modules.

---

core/parser.mly
tests/alien.tests

This patch provides an easy fix for #604 by disallowing alien blocks
syntactically below the top-level. Incidentally this makes the alien
and alien blocks more coherent as it is already the case that the
former cannot appear below the top-level.
Note that alien and alien blocks can still appear below the global
top-level if they appear in a local module. However, they are still
syntactically at the "top-level" of the said module.
Fixes #604.

Disallow alien blocks below top-level

---

core/compilePatterns.ml
core/parser.mly
core/sugarConstructorsIntf.ml
core/sugarTraversals.ml
core/sugartoir.ml
core/sugartypes.ml
core/transformSugar.ml
core/typeSugar.ml
examples/handlers/light_switch.links
examples/handlers/nim-webversion.links
examples/handlers/number_games.links
examples/handlers/pi.links
examples/handlers/racing-lines.links
examples/handlers/sat.links
examples/handlers/sierpinski-triangle.links
examples/handlers/transaction.links
tests/handlers.tests

This patch generalises the kind of expression which is allowed to
appear in the expression position of a parameter binding form in a
parameterised handler. It was necessary to slightly change the syntax
of parameter binding to allow every expression form. Previously the
binding form syntax was
logical_expression -> pattern
now it is
pattern <- expression
The syntactic swap between the expression and pattern was necessary to
avoid a parser conflict.
The patch also rectifies a bug with shallow handlers which meant the
empty clause set was not allowed.

[Handlers] Generalise parameterised handlers.

---

core/basicsettings.ml
core/desugarCP.ml
core/desugarCP.mli
core/desugarDatatypes.ml
core/desugarDatatypes.mli
core/desugarFormlets.ml
core/desugarFormlets.mli
core/desugarFors.ml
core/desugarFors.mli
core/desugarFuns.ml
core/desugarFuns.mli
core/desugarInners.ml
core/desugarInners.mli
core/desugarPages.ml
core/desugarPages.mli
core/desugarProcesses.ml
core/desugarProcesses.mli
core/desugarRegexes.ml
core/desugarRegexes.mli
core/desugarSessionExceptions.ml
core/desugarSessionExceptions.mli
core/frontend.ml
core/transformSugar.ml
core/transformSugar.mli

This PR does three things:
1. The pipelines in `Frontend` were previously expressed as big, composed functions. I replaced this with lists of functions.
2. The types of the transformations are simplified. Many of the transformations that run after type-checking returned a triple, where only one value was actually relevant. In addition, there was some awkward logic in place to make sure that the type environment determined by `TypeSugar` is the one returned by the overall pipeline.
3. There is now a setting `recheck_frontend_transformations`, which if enabled repeats type-checking after each transformation that happens after type-checking. This is something @slindley was particularly interested in.
Note that the functions `program` and `interactive` share quite some overall logic, but they …

Frontend.ml refactoring

---

core/basicsettings.ml
core/desugarDatatypes.ml
core/lib.ml
core/parser.mly
core/sugarConstructors.ml
core/sugarConstructorsIntf.ml
core/types.ml
core/types.mli
prelude.links
tests/functions.tests
tests/functions.tests.effect_sugar.config
tests/functions.tests.shared_effect_vars.config

See #566 for a bit of a deeper explanation.
- Remove fresh name generation from the parser, just generating a placeholder variable. Fresh variable names are now generated as part of `DesugarDatatypes`.
- Add a `shared_effect_vars` flag. When enabled, functions with no explicit effect variables will use the same effect variable. For example, `map : ((a) -e-> b, [a]) -e-> [b]` can be written as `map : ((a) -> b, [a]) -> [b]`.
- Start some work on allowing printing types as above. This requires a bit more thought before it's actually usable, so happy to revert it for now.
A couple of things worth mentioning/I'm not entirely happy with:
- `shared_effect_vars` isn't a fantastic name, so any ideas are appreciated.
- We need to disambiguate between "explicit but unnamed" effect variables …

Syntactic sugar for effect variables in higher-order functions

---

core/dune
core/lib.ml
core/lib.mli
core/proc.ml
core/proc.mli
core/utility.ml
core/webserver.ml
links.opam

This patch replaces `websocket-lwt` with `websocket-lwt-unix` to
enable Links to work with the latest versions of its dependencies.
Links depends on [OCaml Websocket library](https://github.com/vbmithr/ocaml-websocket) and its
sublibrary `websocket-lwt`. However, `websocket-lwt` has become stale,
meaning that packages which share common dependencies with
`websocket-lwt` no longer can be upgraded.
It seems that `websocket-lwt` has been superseeded by
`websocket-lwt-unix`, which happens to provide a slightly different
interface.

Upgrade Websocket dependency

---

azure-pipelines.yml

It seems that the `brew` package manager might be somewhat unstable. An update to `brew` overnight has introduced a regression on the CI image for macOS, which means the postgresql service no longer starts.
What follows is a series of ridiculous attempts to fix the macOS database installation regression.
Related #584.

[CI] macOS database installation regression

---

core/evalir.ml
core/json.ml
core/resolveJsonState.ml
core/value.ml
core/value.mli
tests/alien.tests

- Add an `` `Alien`` case to the value representation - this currently carries no additional information.
- When evaluating an alien binding within the interpreter, we bind an `` `Alien`` value instead (fixes #281).
- Obviously aliens may have any type, and so can be used anywhere (called as a function, projected/extended, etc...) so this PR also attempts to improve the error messages one gets when performing operations on unexpected values.

Bind Alien values in the IR

---

core/errors.ml
core/errors.mli
core/js.ml
core/lexer.mll
core/typeSugar.ml
links-mode.el
tests/alien.tests
tests/bindings.tests
tests/variants.tests

This patch extends the definition of `def_id` such that identifier names may contain primes/single-quotes. However, the initial character of an identifier may not be a prime. Thus one may write `var x' = 42;` but not `var 'x = 42;`.
There is one exception: identifiers for alien things may not contain primes, this restriction is due to our current compilation scheme for aliens, where we expect their Links source names to be the same as their JavaScript source names, but sadly JavaScript does not permit primes in identifier names (yet).

Allow primes/single-quotes in identifier names

---

.travis.yml

Supposedly Travis supports Ubuntu 16.04 LTS now, let's see...

[CI] Travis: Upgrade Trusty -> Xenial

---

core/chaser.ml
core/desugarAlienBlocks.ml
core/desugarModules.ml
core/moduleUtils.ml
core/parser.mly
core/sugarConstructors.ml
core/sugarConstructorsIntf.ml
core/sugarTraversals.ml
core/sugartypes.ml

This patch changes the representation of modules to emphasise that
they are nominal. Previously modules would just have structural names,
whilst with this patch each module gets its own binder.
This is a prerequisite for #603.

Nominal modules.

---

core/chaser.ml
core/compilePatterns.ml
core/desugarCP.ml
core/desugarFuns.ml
core/desugarInners.ml
core/desugarSessionExceptions.ml
core/dumpTypes.ml
core/sugarConstructors.ml
core/sugarTraversals.ml
core/sugartoir.ml
core/sugartypes.ml
core/transformSugar.ml
core/typeSugar.ml
core/types.ml

This patch makes the frontend representation of binders abstract. It
turns out that an abstract representation is convenient for enabling
the proper module system (#603) to live along side the current module
system as the former benefits from a slightly richer notion of
binders.
I also changed the internal representation of binders, as before the
type component was an option type. There is no need to have an option
type, since we can use the dummy type **\`Not_typed** to denote
absence. The dummy type should never occur in an actual program, but
it turns out not to be true in the current implementation of session
exceptions, however @SimonJF's patch #621 seems to rectify this.
Related #603.

Abstract binders

---

examples/mvu/mousetest.links
test-harness
tests/typecheck_examples.tests

There was a small error in one of the MVU files which slipped through the CI because of a combination of a misconfiguration in one of the tests files, and a bug which meant that a failure was not reported.
This patch fixes the error in the MVU example, fixes the misconfiguration, and also fixes the issue in the `test-harness` file which allowed it to slip through undetected.
(Arguably, the `config` check shouldn't be there, since it would be nice to override the default config. But that's for a different patch.)

Fix CI for MVU and address bug in harness

---

.gitattributes
examples/.gitattributes

I ran into a bizarre problem with `tests/dos-newlines.links` showing changes in my local repository, I observed this on Mac OSX and Linux even after doing new clones.  After discussion with @slindley and looking at #503 it seems that the current configuration is too aggressive and may be leading to inconsistent states.  This changes the configuration so that by default all files are treated as text, with automatic newline replacement (this should mean that whatever is native is used for local files, but translated to CR on the repository).  The exception is tests/dos-newlines.text, which is specified to use CRLF.  (The version in the repository still is stored using CR, but the local file copy is stored as CRLF).
This worked for me, but  needs to pass the CI and be tested by people using …

[WIP] attempt to fix newlines configuration

---

links-mode.el

I've been having some weird issues with `links-mode`, where highlighting would stop working after encountering XML tags. It appears that the font-lock keyword listing was using faces which don't exist (at least on my Emacs setup), and so were crashing the syntax highlighter.
Changing the face names appears to fix this - I'm just using function name instead of XML (which is what `mhtml-mode` appears to use), and the default face for XML attributes. It's still not perfect, but it's a definite improvement.

Fix links-mode using non-existent faces

---

core/parser.mly
tests/records.tests

A feature I've been missing from OCaml is record field punning. In
OCaml, we can write:
```
let hello = "hello!" in
{ hello; world = 5 }
```
instead of
```
let hello = "hello!" in
{ hello = hello; world = 5 }
```
This patch is a simple parser hack to allow the same sort of thing in
Links. We can't do field punning directly since we get a reduce/reduce
with a parenthesised expression, but we can delineate punned fields with
an operator (I chose a colon), allowing us to write:
```
var hello = "hello!";
(:hello, world = 5)
```
which is parsed in as
```
var hello = "hello!";
(hello = hello, world = 5)
```

Record field punning

---

dune

This is a small amendum to #668 - sorry, I should have picked this up earlier.
The dev profile by will error on most warnings by default. While additional strictness may be useful, it can be some little frustrating as non-fatal issues cause the build to fail (and make editor error highlighting a little more confusing).
We use `-warn-error -a+31` (the default setting for ocamlc) to prevent these warnings from erroring.
This change also allows us to build Links in development mode on 4.08 (albeit with it warning on `bin/repl.ml`).

Fix warnings being fatal in development mode

---

lib/js/vdom.js
lib/stdlib/mvuAttrs.links
lib/stdlib/mvuHTML.links

Minor patch: currently the MVU library only supports escaped text nodes (for example, showing raw HTML and "&"-coded symbols). Sometimes this is too restrictive (like in my GtoPdb clone).
This patch allows you to do
```
unescapedTextNode("&amp;")
```
for example, which will correctly come out as an ampersand. The trick is to have a `span` tag and set its `innerHTML` attribute.
The patch also contains a fix to the `for` attribute (the library works using properties rather than attributes generally, so it must be `htmlFor` rather than just `for`).

MVU: Unescaped text nodes

---

core/lexer.mll
core/xmlLexer.mll
tests/xml.tests

Modern HTML allows hyphens in attributes. Take this Bootstrap code:
```
<button class="navbar-toggler" type="button" data-toggle="collapse"
data-target="#navbars" aria-controls="navbars"
aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>
```
This small patch allows hyphenated attributes in Links.

Allow hyphenated HTML attributes

---

lib/stdlib/mvuAttrs.links

Small patch: currently `onChange` takes an event handler function of type `() -> Message`. This patch changes it to `(String) -> Message`, where `String` is the `value` attribute of the element. This makes `onChange` useful for things like dropdown menus.

MVU: Make onChange event handler take DOM value as a parameter

---

core/lib.ml

The builtin function `show` has an impure effect signature (`(a) ~> String`), yet it was marked as `PURE` in `lib.ml`, meaning that the JavaScript compiler would not CPS transform the function.
This patch marks the function as `IMPURE` in `lib.ml`.
Resolves #689.

Fixes compilation of `show`.

---

core/desugarFuns.ml
core/desugarInners.ml
core/lexer.mll
core/liftRecursive.ml
core/parser.mly
core/sugarConstructors.ml
core/sugarConstructorsIntf.ml
core/sugarTraversals.ml
core/sugartypes.ml
core/typeSugar.ml

This allows writing "frozen function definitions", which will never generalise their types:
```
~fun f(x) { x }
```
The major issue with this change right now is that you can write mutual blocks with one frozen function and one-non frozen one, allowing definitions like:
```
mutual {
~fun f(x) { x }
fun g(x) { f(x) }
}
```
This now causes quantifiers to escape their scope, similar to #678, meaning `f` uses the quantifiers bound by `g`'s type.

Frozen lets

---

core/desugarDatatypes.ml
core/desugarInners.ml
core/parser.mly
core/sugarTraversals.ml
core/sugarTraversals.mli
core/sugartoir.ml
core/sugartypes.ml
core/transformSugar.ml
core/typeSugar.ml

This adds syntax for explicit type applications. One may now write:
```
~id[Int] # Produces a type ∀ e. (Int) -e-> Int
~id[Int, {}] # Produces a type (Int) {}-> Int
```

Add syntax and type checking for type applications

---

core/parser.mly

Record definitions allow fields like the following:
(foo: Int, "returning": Bool)
for field names like "returning" which are keywords. However, these
quoted field names were not allowed in relational lens expressions.

Allow quoted field names in lens expressions

---

lib/js/jslib.js

Fixes #670. 
The issue was that the `addAttributes` function was not correctly implemented. Since I don't think any of us were aware of the sugar for allowing attribute lists, nobody noticed!
This patch correctly implements the logic needed for `addAttributes` to work.

Fix addAttributes

---

core/basicsettings.ml
core/webserver.ml

The handling of `jsliburl` was buggy in that slashes weren't properly handled in the case of a non-empty base URL. This manifested itself in lots of errors for new users who did not have `jsliburl` explicitly set to `/lib/`.
This patch fixes the handling (and the default value of the property) so the config need not explicitly contain `jsliburl` anymore.

Fix default jsliburl handling

---

core/page.ml
lib/js/jslib.js

This patch instruments the Links web runtime with a "readiness check"
before calling `_startRealPage`. If the readiness check fails it emits
an error message (in HTML) and discontinues the start up process. As a
consequence Links will no longer render the user-defined webpage in
the event of the runtime dependency `jslib` failing to load. Instead the following error message is displayed:
```
<h1>Startup error: Runtime dependency `jslib.js' is not loaded.</h1>
```
Currently, the readiness check only checks whether `jslib` is
loaded. It could be extended to check whether alien JavaScript sources
have been loaded too. However, I think the page compiler is due a
refactor before we go down that path.
Resolves #590.

Display an alert if `jslib` fails to load.

---

links-mysql.opam.unsupported
links-postgresql.opam
links-sqlite3.opam

We require `dune` as a build-time dependency. In our `dune-project`
file we specifically state that we use `dune` version `1.10.0` (I am
not sure whether that is strictly true, I suspect it may be an
over-approximation). However, in our `.opam` files we do not state any
bound on `dune`, hence OPAM is let to believe that Links can be built
using older versions of `dune`.
This patch makes explicit in the `.opam` files that we require at
least version `1.10.0` of `dune` to build Links.

Specify the compatible version range of `dune`.

---

core/basicsettings.ml
core/webif.ml
core/webif.mli

The option `realpages` used to govern whether Links would serve
web pages built on the server or build them dynamically on the 
client. The option appears to have been unused (and unsupported)
for a while. Although, the default value of `realpages` was `false`
the Links appserver would always serve pages built on the server.
This patch removes the option altogether.

Remove the option `realpages`.

---

links-mysql.opam.unsupported
links-postgresql.opam
links-sqlite3.opam
links.opam

[Supposedly `dune` no longer satisfies the OPAM definition of a build-time dependency](https://github.com/ocaml/opam-repository/pull/14501#issuecomment-515951073),
hence we should make it a runtime dependency.
This patch removes `build` tag from the `.opam`-files such that `dune`
becomes a runtime dependency.

Untag `dune` as a build-time dependency.

---

core/backend.ml
core/basicsettings.ml

This patch resolves #561 by separating the type structure
simplification pass from the IR type checker. A new flag
`simplify_types` is introduced which dictates whether the
simplification pass is run -- well that is, it runs if the flag is set
or `typecheck_ir` is set as I am not sure whether the IR type checker
depends on the simplification pass.
The patch also fixes a couple of issues with side effects in the IR
backend pipeline infrastructure. As settings `typecheck_ir` and
`show_compiled_ir_after_backend_transformations` had no effect if
Links was not booted with those settings set to true, meaning that
they could not be toggled from within the REPL. This is rectified by
replaying the side effects whenever a backend pipeline is invoked.

Decouple IR type structure simplifications from IR type checking.

---

core/basicsettings.ml
links.opam

Now that Links 0.9 is released, we can bump revision number such that development happens on 0.9.1.

Bump development version 0.9 -> 0.9.1

---

run-tests
test-harness

This patch moves the logic for discovering configs associated with
test scripts from `run-tests` into `test-harness`. As a result
`./test-harness tests/<testname>.tests` will now run correctly when
the tests are expected to be run with a particular configuration.
Resolves #720.

Restore the constancy between `run-tests` and `test-harness`.

---

core/proc.ml

This patch is a response to ocsigen/lwt/issues/603. Lwt 5.0.0 will
introduce a breaking change as the signature of `Lwt.async` changes
from
```ocaml
val async : (unit -> 'a Lwt.t) -> unit
```
to
```ocaml
val async : (unit -> unit Lwt.t) -> unit
```
This patch simply post-composes `>>= fun _ -> Lwt.return_unit` to the
bodies of the function arguments where necessary.

Prepare for Lwt 5.0.0.

---

test-harness
tests/freezeml.tests
tests/typed_ir.tests

This patch aims to remove some of the "magic" in the test suite
runners. Specifically, this patch augments our ad-hoc testscript
language with an optional header section, which contains key value
pairs (currently only "config: path/to/file.config" is supported) that
can be used to fix parameters globally for the tests in the respective
script. So if a script uses a particular config file it has to be
listed explicitly in the script header.
Syntactically a header is surrounded by a pair of `---` followed by a
blank line. A header may only contain key-value pairs of the form
`key: value`. This syntax is adopted directly from the Markdown header
format. Example:
```
---
config: tests/typed_ir.tests.config
---
Anonymous constant function
fun(x) {1}
stdout : fun : (_::(Unl,Mono)) -> Int
```
It …

Endow testscripts with an optional header section.

---

core/lib.ml
lib/js/jslib.js

This simple patch adds the `log10` function, found in both the OCaml and JS libraries, to Links.

Add log10 function

---

core/desugarSessionExceptions.ml

There is an arbitrary choice as to whether to compile session exceptions
using deep or shallow handlers. I switched this to Shallow at some
point, and since then it seems that shallow handlers no longer compile
on the client.
(Unfortunately, this means that session exceptions are broken in 0.9).
This patch switches them back to deep.

Compile session exceptions using deep handlers

---

core/channelVarUtils.ml
core/closures.ml
core/commonTypes.ml
core/evalir.ml
core/ir.ml
core/ir.mli
core/irCheck.ml
core/irTraversals.ml
core/lexer.mll
core/parser.mly
core/query/evalNestedQuery.ml
core/query/evalQuery.ml
core/query/query.ml
core/query/query.mli
core/sugarConstructors.ml
core/sugarConstructorsIntf.ml
core/sugarTraversals.ml
core/sugartoir.ml
core/sugartypes.ml
core/transformSugar.ml
core/typeSugar.ml
examples/handlers/pipes.links
tests/database.tests

This patch allows the specification of whether a query should be treated as flat or shredded on a per-query basis. The patch extends query syntax as follows:
```
query [range] policy {
...
}
```
where `policy` is either `plain`, `nested`, or omitted. If `plain` is used, then the query will evaluated using the default evaluator, and if `nested` is used, then the query will be shredded. If the policy is omitted, then the `shredding` setting is used to decide, as before.
This allows us to have applications which use shredded queries by default, but also have queries which use ranges, ordering, or regexes.

Support flat and shredded queries simultaneously (Fix #538)

---

examples/mvu/commands.links
examples/mvu/keypress.links
examples/mvu/mousetest.links
examples/mvu/pong.links
examples/mvu/time.links
lib/stdlib/dune
lib/stdlib/mvu.links
lib/stdlib/mvuCommands.links
tests/typecheck_examples.tests

Commands in Elm allow side-effecting computations to be performed inside the MVU event loop. A particularly important side-effect is to spawn a computation which evaluates asynchronously, returning a message when it is complete.
This patch adds commands to the Links MVU library. It's existed in various branches of mine for a while, but I'm finding it necessary for the GtoPdb curation tool so thought it might be nice to have it in master. I'd say the primary use right now is to allow RPCs and MVU to coexist nicely.
Key changes: 
- add a new type, `Command(Message)` which describes a computation which will produce a message of type `Message`
- revise most general type of `updt` function from `(Message, Model) ~> Model` to `(Message, Model) ~> (Model, Command(Message))`
You can see the gist …

MVU: Commands

---

core/types.ml

In `types.ml` the following definition `dummy_type = Primitive Int` is
used as an initial placeholder meant to be replaced later by a real
type during type dualisation.
Given that we have a "dummy" type in our type algebra, namely
`Not_typed`, it seems rather silly to use a real type instead as the
type infrastructure is set up to fail if it encounters the
`Not_typed`. Thus this minor patch changes the definition of
`dummy_type = Not_typed` which is potentially a safer placeholder
value.

A 'safer' dummy type.

---

tools/rule-check

It seems that the recent upgrade of OCamlformat 0.11 to 0.12 every
file under scrutinty fails.breaks our rule check script.
I can reproduce this problem locally on my machine. This commit is
currently empty to reproduce it on the CI.

Disable ocamlformat check

---

azure-pipelines.yml

It seems there have been two changes to either `brew` or the macOS
version on Azure Pipelines lately. It seems that the macOS image now
ships with `python` version `3.7.5` which also appears to be the
latest version maintained by the `brew` repository that we are
using. Apparently the command `brew upgrade python` fails whenever the
installed `python` package is up-to-date.
Thus this patch simply removes the `brew upgrade python` step.

Fix installation of `python3` on Azure Pipelines macOS image (again).

---

bin/driver.ml
bin/repl.ml
core/compilePatterns.ml
core/defaultAliases.ml
core/desugarCP.ml
core/desugarDatatypes.ml
core/env.ml
core/env.mli
core/instantiate.ml
core/irCheck.ml
core/irTraversals.ml
core/irtojs.ml
core/lens_ir_conv.ml
core/lib.ml
core/page.ml
core/query/query.ml
core/sugartoir.ml
core/transformSugar.ml
core/typeSugar.ml
core/var.ml
core/webserver.ml

This patch changes the signature of `Env.S` to allow for a more
efficient implementation of environments. For performance reasons it
changes the signature of `bind` from
```ocaml
bind : 'a t -> (name * 'a) -> 'a t
```
to
```ocaml
bind : name -> 'a -> 'a t -> 'a t
```
That is the `bind` now takes all its arguments in curried form. This
reduces the amount of necessary memory allocations by one per
invocation of `bind` (which is called a lot). For aesthetics and
coherence the data container (i.e. the environment of type `'a t`) is
now the last parameter. This aligns with the "standard" functional
APIs (e.g. `Map`) rather than the "standard" imperative APIs which
take the data container as their first argument (e.g. `Hashtbl`).
Moreover, this change also aligns the interface with `Map`, …

An efficient interface for `Env`.

---

core/typeSugar.ml

This patch introduces a thin abstraction for variable usage tracking
in the frontend type checker. Usages are now manipulated via a
structured interface `Usage`, as a result it is no longer necessary
(nor possible) to manipulate them on an ad-hoc basis via bare
`StringMap`s, `StringSet`s, and lists.
This code is extracted and adapted from the name hygiene patch which I
have been working on lately. I think this code is useful on its own as
it makes the type checker more robust. Ancedotally, I did find and fix
a couple of linearity bugs in the implementation of effect handlers
and session exceptions, where usage weren't tracked properly.
This patch adds a small compatibility module `Ident` which is
essentially an artefact of my hygienic names patch. I have added it to
make it easier for me …

Structured variable usage tracking.

---

core/buildTables.ml
core/closures.ml
core/commonTypes.ml
core/desugarAlienBlocks.ml
core/desugarDatatypes.ml
core/desugarModules.ml
core/errors.ml
core/errors.mli
core/evalir.ml
core/ir.ml
core/ir.mli
core/irCheck.ml
core/irTraversals.ml
core/irtojs.ml
core/moduleUtils.ml
core/parser.mly
core/sugarTraversals.ml
core/sugarTraversals.mli
core/sugartoir.ml
core/sugartypes.ml
core/transformSugar.ml
core/transformSugar.mli
core/typeSugar.ml
core/value.ml
tests/alien.tests

This patch refactors the frontend implementation of FFI. The changes
are only cosmetic.
This is backported from my work on name hygiene/compilation
units. Ultimately, I would like to use the FFI to bootstrap (in the
frontend) the Links builtins library (aka `lib.ml`). By doing this
`lib.ml` need not be treated specially by the frontend, which makes it
significantly easier to implement a uniform infrastructure for
compilation units.

Foreign Function Interface clean up.

---

core/parser.mly

This patch extends the grammar of Links such that the empty program is
accepted by the parser as a syntactically valid program.
It is useful to be able to start Links with an empty prelude, e.g. for
debugging. We already accept the empty expression as valid input in
interactive mode.

Accept the empty program as a valid Links program.

---

core/typeSugar.ml

This patch aligns the error message for unbound section names with
that for unbound variable names. Previously, Links would print a "raw"
exception for unbound section names, for example assuming `@@` is an
undeclared binary operator, then
```links
links>2 @@ 2;
***: Error: Links_core.Errors.UndefinedVariable("Variable '@@' does not refer to a declaration")
```
With this patch Links will print the same message as for undefined
variables:
```links
links>2 @@ 2;
test.links:1: Type error: Unknown variable @@.
In expression: 2 @@ 2.
```

Improve error message for unbound section names.

---

bin/repl.ml
core/commonTypes.ml
core/evalir.ml
core/irtojs.ml
core/json.ml
core/lens_ir_conv.ml
core/lexer.mll
core/parser.mly
core/query/query.ml

This patch removes the `native` location which, judging from the
source code, never seems to have been implemented. I seem to recall
that values marked native were intended to be FFI-like, i.e. their
implementations were to be given outside of Links. We already support FFI calls
to JavaScript via `alien` declarations. I think further development of
FFI should happen on `alien`.
This patch garbage collects the keyword `native`, that is, it can now
be used as an identifier.

Remove `native` location.

---

core/frontend.ml

Recent changes to `Frontend` introduced a bug where the AST printed after the frontend transformations ran (enabled by setting `show_post_frontend_ast`) was actually the original AST.

Show correct post-frontend AST when setting for it is enabled

---

core/sugartoir.ml
core/typeSugar.ml
tests/functions.tests

In an anonymous function only the last argument can be linear. This patch is based on #796.
Fixes #795

Correctly handle linearity of arguments in lambdas

---

core/lib.ml
lib/js/jslib.js
prelude.links
tests/char_operations.tests

This patch removes the following character operations from `lib.ml`
and implements them in Links itself (they are now defined in
`prelude.links`):
* `toUpper : (Char) -> Char`
* `toLower : (Char) -> Char`
* `isUpper : (Char) -> Bool`
* `isLower : (Char) -> Bool`
* `isDigit : (Char) -> Bool`
* `isAlnum : (Char) -> Bool`
* `isXDigit : (Char) -> Bool`
* `isBlank : (Char) -> Bool`

Implement character operations in Links.

---

core/lib.ml
tests/builtins.tests

We have the `log` function in `lib.ml`, but not its inverse `exp`. Now we do.

Add the `exp` function to `lib.ml`

---

lib/js/jslib.js

To supplement #800: the `exp` function needs to be added to the JavaScript runtime too.

Add `exp` to jslib too.

---

.travis.yml
azure-pipelines.yml
core/evalir.ml
core/proc.ml
core/proc.mli
core/utility.ml
core/value.ml

The continuous integration seems broken since Lwt 5.*. It produces the
following error
```
#=== ERROR while compiling lwt.5.1.1 ==========================================#
```
However, I cannot seem to reproduce this error locally.

LWT 5 support

---

tests/operators.tests

This commit adds a few associativity and precedence tests. The source
of truth is taken to be the current implementation of operator
precedence and associativity parsing. Nevertheless, we may want to
change the precedence of some operators as there are a few surprising
cases.

Operator associativity and precedence tests.

---

bin/repl.ml

Prior to this patch, defining two functions with the same name would
only cause the former to be printed by the REPL, e.g.
```
links> fun f(x) { x };
f = fun : (a::Any) -> a::Any
links> fun f(x) { x };
links>
```
With this patch the REPL will also print the latter entry.
The previous implementation would simply diff the previous compiler
context and the current compiler context to determine which names were
new. However, this is not sufficient to tell whether a name has been
redefined as long as the internal names are not hygienic.
This patch refines the diffing approach:
- For values the REPL computes the set of new IR vars -- which are
globally unique -- and uses those to determine whether a name has
been redefined, and thus should be printed.
- As for typenames, the REPL makes use of a …

Always print redefined value names and typenames in the REPL.

---

core/compilePatterns.ml
tests/patterns.tests

This patch resolves #810 by implementing a compilation rule for
negative patterns in let expressions. The implementation simply
expands a negative pattern match into a switch-case expression as
follows.
```
[| var -(l1,...,lN) = value; body |]
= switch (value) {
case l1 -> Wrong
...
case lN -> Wrong
case _  -> body
}
```

Fix compilation of negative patterns.

---

core/query/query.ml

This is a tiny fix for an overlooked detail in the `Query.compile_delete`. Unlike its sibling `compile_update`, this was trying to generate SQL without performing normalization first.

Fixes #807

---

dune

Our codebase triggers numerous instances of warning 67 with OCaml
4.10.0. This patch fixes those instances such that our codebase no
longer emits any warnings under any of our compilation profiles.

Fix compilation warning 67 emitted by OCaml 4.10.0

---

core/context.ml
core/desugarModules.ml
core/frontend.ml
core/lexer.mll
core/operators.ml
core/parser.mly
core/shunting.ml
core/sugarTraversals.ml
core/sugartoir.ml
core/sugartypes.ml
core/transformSugar.ml
core/typeSugar.ml
tests/fixity.links
tests/operators.tests

Prior to this patch the associativity and precedence of user-definable
operators would be stored in the internal state of the lexer. This
state was not preserved between invocations of the lexer on per
compilation unit and per REPL entry. As a consequence, during
subsequent parses every previously defined operator would default to
be left associative and have precedence 9.
This patch removes the operator associativity and precedence
information from the lexer. Instead of handling associativity and
precedence in the lexer and parser, they are now handled by the
transformation `shunting` which applies a variation of the Shunting
Yard algorithm on expressions. The transform uses our transformation
infrastructure to preserve and pass an operator table between
subsequent invocation of this …

Operator associativity and precedence

---

core/lexer.mll
core/parser.mly

This patch resolves #815 by introducing a distinguished end-of-file
token. Furthermore, this patch also garbage collects `End` as a
keyword to allow it to appear as a variant label at the term level. At
the type level `End` is still interpreted as the end datatype.
The below snippet illustrates various uses of `End`.
```
links> End;
End : [|End|_::Any|]
links> sig f : (End) ~> () fun f(x) { close(x) };
f = fun : (End) ~> ()
links> sig g : ([|End|]) ~> () fun g(_) { () };
g = fun : ([|End|]) ~> ()
links> sig h : ([|End:End|]) ~> () fun h(End(x)) { close(x)  };
h = fun : ([|End:End|]) ~> ()
```

Distinguished end-of-file token.

---

bin/links.ml
core/desugarDatatypes.ml
core/desugarEffects.ml
core/desugarEffects.mli
core/desugarTypeVariables.ml
core/desugarTypeVariables.mli
core/errors.ml
core/errors.mli
core/frontend.ml
core/lib.ml
core/parser.mly
core/renamer.ml
core/sourceCode.ml
core/sourceCode.mli
core/sugarTraversals.ml
core/sugarTraversals.mli
core/sugartypes.ml
core/transformSugar.ml
core/typeSugar.ml
core/types.ml
core/types.mli
tests/functions/escaped-quantifier.links

This PR splits DesugarDatatypes into 3 individual, self-contained passes. I found this to be a necessary step to continue my work on explicit type abstractions, as `DesugarDatatypes` had become an unmaintainable mess doing too many things at once. The new passes only perform a single, dedicated task each. This should make them easier to understand and maintain.
The new passes are the following:
1. `DesugarTypeVariables` "resolves" type variables, meaning that it determines their scope and replaces  their syntactic representation (i.e., their string name) with a `Unionfind` point.
Even though `DesugarTypeVariables` works very differently from how type variables were resolved before, the goal of this PR is not to change the scoping behavior of type variables. I'll make those changes in a …

Refactoring DesugarDatatypes into different passes

---

core/desugarFors.ml
tests/typed_ir/T698.links

Consider the expression `for (x <-- t) [x]`
where `t` has type `TableHandle(a,b,c)`
This currently desugars roughly to
```
concatMap(
(fun (x : TableHandle(a,b,c))  {[x]}),
(asList t))
```
However, this is wrong, because the type of `x` in the lambda should be `a` rather than  `TableHandle(a,b,c)`, because we wrap `t` in `AsList`
These desugarings happen after `TypeSugar`, which is why we only detected this as an IR type error (#698). Hence, this fixes #698.

Fix type ascription in lambda generated for comprehension bodies

---

test-harness

Currently, the test harness detects if a test case times out, but fails to actually kill the Links process executing the timed-out test case.
The only minor caveat is that the test harness doesn't spawn the Links processes directly. Instead, it creates a shell which in turn starts the Links process. Hence, killing just the shell after a timeout leaves the Links process running. Therefore, I had to add some process group magic such that we can easily kill the shell and all of its sub-processes (i.e., the Links process).

test suite: kill offending Links process in case of timeout

---

tests/typed_ir.tests

In another PR, @jstolarek observed that I had created a test file for an IR test, but forgot to register it in `typed_ir.tests`. The same problem happened in #820, where I added a test for  #698.

Properly register test for #698 in typed_ir.tests

---

.ocamlformat
.travis.yml
azure-pipelines.yml
tools/install_ocamlformat
tools/rule-check

This branch updates our `.ocamlformat` file to be compatible with Ocamlformat 0.14.1. It also fixes ocamlformat to version 0.14.1 so that any future compatability updates don't affect the codebase. I've moved the installation of ocamlformat to `./tools/install_ocamlformat` which is then used by both `.travis.yml` as well as `azure-pipelines.yml`.

Remove Ocamlformat from blacklist

---

Makefile
core/database.ml
core/database.mli
core/evalir.ml
core/query/evalQuery.ml
core/query/query.ml
core/query/query.mli
core/query/sql.ml
core/value.ml
core/value.mli
database/mysql-driver/mysql_database.ml
database/pg-driver/pg_database.ml
dune

Previously, SQL update and deletion operations were constructed as strings in `query.ml`. Since insertions are implementation-dependent, the picture there is even worse: we needed to do some gymnastics to get a bunch of strings, which were then passed to the `Value.database` implementation.
When we're wanting to do query rewrites (say, if we wanted to do temporal database operations, for example), the string-based approach is very inflexible. Furthermore, insertions are treated non-uniformly, which is a pity.
This patch adds abstract syntax for SQL insertions, updates, and deletions in the `Sql` module, and adapts the rest of the codebase to use them. More specifically:
- `Sql` contains the new abstract syntax nodes `Insert`, `Update`, and `Delete`.
- `Sql.string_of_query` takes a field …

Abstract syntax for SQL modifications

---

core/frontend.ml
core/query/query.ml
core/sugartoir.ml
core/typeSugar.ml
core/wrapTableIterators.ml
core/wrapTableIterators.mli
tests/database.tests
tests/database/factorials.links
tests/shredding/factorials.links
tests/shredding/factorials.sql
tests/shredding/testsuite.config

This patch partially addresses #835, in particular:
```
query flat { for (x <--factorials) [(a=x.i,b=x.f)]};
query flat { for (x <- asList(factorials)) [(a=x.i,b=x.f)]};
```
These queries (explicit `flat` modifier) did not run as expected when `shredding` was set to true. The reason for this is that all `Iteration` nodes are implicitly wrapped in a `Query` block if they contain a table generator, and unannotated query blocks took the evaluation policy set by the `shredding` option. Thus:
```
query flat { for (x <--factorials) [(a=x.i,b=x.f)]};
```
was effectively transformed into
```
query flat { query nested { for (x <--factorials) [(a=x.i,b=x.f)]} };
```
causing a mismatch.
This patch fixes this in two ways. Firstly, inner `default` query blocks take the evaluation policy of the outer …

Partially fix #835

---

.travis.yml
azure-pipelines.yml

What the title says. If the working tree isn't clean after cloning (e.g. because newlines are automatically converted in a way they shouldn't -see #5030) CI will catch it. Closes #507.

Test for a clean clone as part of CI

---

bin/links.ml
bin/repl.ml
core/basicsettings.ml
core/evalir.ml
core/typeSugar.ml
core/webserver.ml

Links originally supported running in "web mode" as a stateless CGI script.  
This was replaced by the appserver and removed as of #313.  However, a few vestiges remain, largely the `-w` flag and `web_mode` setting, which was only being used to determine whether to pretty-print REPL output and whether to print error messages as plain text or HTML.  Moreover, `web_mode` was being set either by the `-w` flag, by the presence of the CGI `REQUEST_METHOD` environment variable, or automatically when the app server starts.
There is a separate setting, `Webserver_types.webs_running`, which is also set when the app server starts, and can never be unset, thus we can use this to determine whether to pretty-print output or print errors as HTML instead of `web_mode`.  Moreover, the command line or CGI …

remove last vestiges of CGI script web mode

---

core/types.ml
examples/sessions/ap-multi-client.links
examples/sessions/draggable.links
examples/sessions/fusegg.links
examples/sessions/givengrab.links
examples/sessions/gng-client.links
examples/webserver/draggable-sessions.links
prelude.links
tests/session-exceptions/cancel1.links
tests/session-exceptions/cancel10.links
tests/session-exceptions/cancel11.links
tests/session-exceptions/cancel2.links
tests/session-exceptions/cancel3.links
tests/session-exceptions/cancel4.links
tests/session-exceptions/cancel5.links
tests/session-exceptions/cancel6.links
tests/session-exceptions/cancel7.links
tests/session-exceptions/cancel8.links
tests/session-exceptions/cancel9.links
tests/typecheck_examples.tests

As hinted at by a1ffb17f2890a9647d4456be07f303bf2de82ba0, Links was not handling the linearity of the `End` type correctly. This was because of a very subtle bug in checking linearity of dualised session types.
~~This has brought to light what seem to be some rather strange bugs, however. In particular, `examples/sessions/draggable.links` (and by extension `examples/webserver/draggable-sessions.links`) are broken, and I can't see how they would ever have worked: the `mouseUp()` and `mouseDown()` functions request on an AP, do a CP-style selection, and then seem to simply return the channel, which can't be eliminated since the session type does not contain an `End`. Am I missing something here? I've marked as broken examples for now.~~
(fixed the above after some explanation by @slindley)

Fix linearity of `End` in presence of duality

---

core/buildTables.ml
core/channelVarUtils.ml
core/closures.ml
core/compilePatterns.ml
core/ir.ml
core/ir.mli
core/irCheck.ml
core/irTraversals.ml
core/irtojs.ml
core/lens_ir_conv.ml
core/lib.ml
core/query/query.ml
core/sugartoir.ml
core/typeSugar.ml
prelude.links
tests/annotations.tests
tests/typed_ir.tests
tests/typed_ir/T694.links
tests/typed_ir/T697b.links
tests/typed_ir/T698.links

This PR disables the previous code for handling unsafe signatures and implements a new approach:
- `unsafe sig foo` means that the declared identifier is not treated as recursive, for the purpose of effect typing; that is, recursive calls to `foo` are tame.
- type inference is otherwise as normal, and we do not (and do not need to) adjust the inferred type
It also adds treatment of unsafe-signature behavior to the IR.  This unfortunately touches a lot of code because the function definition data is a tuple rather than record.  In IR typechecking, we treat identifiers in recursive blocks as non-recursive if they are declared with `unsafe sig`.
Finally, a remaining problem is that pattern matching against List cons is translated (by `compilePatterns.ml`) to calls to `hd` and `tl`, which are …

Proposal for simpler handling of unsafe sig and fix for #691

---

bin/repl.ml
core/value.ml
tests/xml.tests

This PR fixes a weird bug with pretty-printing XML where spaces were being omitted in unpredictable places.
The reason turns out to be that pretty-printing is actually disabled by default, and this means the default behavior of the formatter used for printing is overridden to ignore newlines and squash indentation or spaces of length longer than 1 to length 1.  However, since `Format` assumes that handling a space hint by generating a newline will result in separating whitespace, this gives undesirable behavior.  Fixing this resulted in further weird behavior, which I've attempted to avoid by also setting the formatter margin and max indent settings to absurdly large values.  
Another thing that seemed to help was enclosing individual `XmlItems` in `Format` boxes when they are encountered …

Fix #256 by adjusting (pretty) printing code

---

Makefile
core/webserver.ml

Currently the makefile produces a bash script which initialises the jslib path to `<something>/lib/lib/<something>` This is fixed by removing `lib/` from the Makefile bit that generates the `./links` script.
For reference the links code that generates the full path: https://github.com/links-lang/links/blob/eaa33ca8c7fb4a7bab85424170379c2250d8ac6c/core/webserver.ml#L314

Fix bug in LINKS_LIB

---

bin/repl.ml
core/buildTables.ml
core/closures.ml
core/compilePatterns.ml
core/evalir.ml
core/irCheck.ml
core/irTraversals.ml
core/irtojs.ml
core/js.ml
core/lens_ir_conv.ml
core/query/query.ml
core/serialisation.ml
core/sugartoir.ml
core/value.ml
core/var.ml
core/var.mli

This patch makes the representation of IR binders abstract, specifically the type definitions `Var.var_info` and `Var.binder`  are abstract, whilst `Var.var` is left concrete for now as making it abstract amounts to a more extensive change. Thus I will leave `Var.var` for a later patch.
The motivation is behind this change is to make it easier to make the notion of binders (and eventually "vars") richer to support #337. This patch includes only the first step. The next step is to make `Var.var` abstract and reorganise the interface of `Var` into two interfaces: one for binders and another for vars.

Abstract IR binders

---

examples/draggableDb.links

This commit fixes a bug in the database version of the draggable lists
example that would cause the list of items to be displayed in inverse
order after a save.

Preserve ordering in Draggable lists (database version) example.

---

core/commonTypes.ml
core/database.ml
core/database.mli
core/evalir.ml
core/irCheck.ml
core/parser.mly
core/query/query.ml
core/query/sql.ml
core/typeSugar.ml
examples/initialise-list.links
examples/relational_lenses/config
examples/relational_lenses/config.sample
tests/database.tests
tests/examples_default.config
tests/examples_effect_sugar.config
tests/examples_session_exceptions.config
tests/shredding/config.sample
tests/shredding/empty.links
tests/shredding/emptyfun.links
tests/shredding/jrules.links
tests/shredding/organisation.links
tests/shredding/travel_portal.links
tests/shredding/unit.links

This pull request:
- removes the shredding and use_keys_in_shredding settings, specializing remaining code to defaults of "shredding=off" and "use_keys_in_shredding=true" (resolves #844).  Since shredding is available by default using `query nested`, this specialization just means that writing `query` on its own defaults to `query flat` and there is no way to change this default behavior.
- updates various configuration and test files to adapt to this change in behavior
- makes minor changes to the recently updated query pretty printing, mostly through adding newlines in the most obvious places.
- finally, generalizes and corrects the treatment of `Select` and `With` in queries following issues noticed in #845:
* `Select` constructors now take a list of `from_clause`s which can be either …

Cleanup query pretty-printing and remove shredding settings

---

core/desugarLAttributes.ml

resolve #217 by improving the error message when l: attributes are used incorrectly

---

core/desugarLAttributes.ml
core/lib.ml
lib/js/jslib.js
prelude.links

This PR adjusts the code inserted when desugaring `l:` attributes.  
On the server side, if an expected `l:` attribute name/id is not present in the field parameters, it is initialized to the empty string.
On the client side, if the element is a checkbox or radio button, then the `value` field is returned only if the `checked` field is true.  Otherwise, the empty string is returned instead.
This fixes #208, but radio buttons/groups of more than one radio button still do not work. See #902, which I'll try to fix as well.

handle checkbox and radio group form elements

---

dune

Following the discussion in #750 this patch drops the `-annot` flag in
place of the `-bin-annot` flag, which seems to be hardcoded into
Dune. However, to ensure our tools continue to work it seems sensible
to supply this flag explicitly.

Update compiler flags

---

core/buildTables.ml
core/closures.ml
core/irCheck.ml
core/irTraversals.ml
core/irTraversals.mli
core/renamer.ml
core/types.ml
core/types.mli

This attempts to fix #776, a tedious refactoring cleanup which I found strangely relaxing.  Keeping as draft since I also wondered whether we might want to further refactor the IR traversals to have the same argument order, see #776.

Fix #776 and reorder irTraversals return values to match

---

core/desugarSwitchFuns.ml
tests/functions.config
tests/functions.tests
tests/switch_functions.config
tests/switch_functions.tests

This commit renames the option `pattern_matching_sugar` to
`switch_functions` as the former is somewhat generic and the latter is
the name of the feature actually being enabled/disabled by toggling
the option.
In addition, this commit also cleans up the test suite for
functions. The non-experimental function features should not be kept
in the same test file as the experimental features -- in particular,
the non-experimental features should not **always** be tested under
the assumption that an experimental flag is enabled.

Rename option to toggle switch functions.

---

CHANGES.md

This is a draft for the changelog for the 0.9.2 release.
I vaguely remember that this release fixes some problem in 0.9.1 where many (all?) web or database examples were broken, but I may be wrong. Does this ring a bell? I went through all commits sine 0.9.1 to create the changelog, but I couldn't find something sounding like that.

Changelog 0.9.2

---

core/closures.ml
core/irCheck.ml
tests/unit/ir/driver.ml
tests/unit/ir/schinks.ml
tests/unit/ir/schinks.mli
tests/unit/ir/schinks_repr.ml
tests/unit/ir/schinks_repr.mli
tests/unit/ir/test_cases/closures.ml
tests/unit/ir/test_cases/closures.mli
tests/unit/ir/test_cases/functions.ml
tests/unit/ir/test_cases/quantifiers.ml
tests/unit/unitTests.ml

This PR 
- removes some comments about the earlier handling scoping of type variables being broken (this was already fixed by @slindley)
- adds test ensuring that the scoping of such type variables is now indeed correct
- adds new features to the IR DSL (closures, records, ...)
- slightly stratifies the types used within the IR DSL
- changes the generation and type-checking of closures such that it coincides with the description in the IR formalization. This only changes that the type of the binder of the closure variable will now carry the quantifiers specific to the closure.
Overall, this doesn't fix any existing bugs, the only difference in behavior is that we can now detect the following, which wasn't possible earlier: When supplying a closure environment to a function as well as type …

Various IR type-checking cleanups

---

tests/unit/ir/schinks.ml
tests/unit/ir/schinks.mli
tests/unit/ir/test_cases/effects.ml

This extends the IR DSL with constructs for dealing with effects. It also adds some test cases for handling the effects of functions, their invocations, and bindings. Luckily, this didn't uncover any bugs.
Note that this doesn't test effect handlers (i.e., `do` and `handle`) themselves.

Testing the IR type-checker's handling of effects

---

lib/js/dune
lib/stdlib/mvu.links
preinstall/preinstall.ml

This commit modifies the install script such that the MVU dependencies
`vdom.js` and `virtual-dom.js` are installed along with the MVU
examples.
To make the MVU examples work out of the box I have chosen to piggyback
on hardcoded resolution for `jslib.js`. This is a horrible hack. I
also had to change the default configuration file to set the stdlib
path in order for the system to find the MVU Links source files.
I was able to run the MVU todo example application on a fresh
installation of Links with the following command.
```
$ linx $OPAM_SWITCH_PREFIX/share/links/examples/mvu/todomvc/todoMVC.links
```
Resolves #930. Resolves #931.

Distribute MVU JavaScript source files.

---

core/query/evalNestedQuery.ml
core/query/query.ml
core/query/sql.ml
database/mysql-driver/mysql_database.ml
tests/database/regexes.links
tests/database/regexes.sql
tests/database/testsuite.json
tests/shredding/jrules.links

(Related in part to #754).
Previously, compiled regular expressions failed at runtime. As an example from GtoPdb:
```
for (strI <-- Tables.structural_info)
where (strI.object_id == objectId && strI.species_id == 2)
for (al <-- Tables.allele)
where (strI.official_gene_id <> "" && al.accessions =~ /.*{strI.official_gene_id}.*/)
```
would fail due to the clause
```
al.accessions =~ /.*{strI.official_gene_id}.*/
```
within the `where` clause, since we're including a regular expression which projects from the `strI` table.
This patch rectifies the above problem for `LIKE`-translatable queries (but not yet for arbitrary `RLIKE` queries).
To fix this, we need to do two things: generalise the return type of `likeify` to include SQL which allows strings, concatenation, and projection operators; …

Allow table projection from within likeifyable SQL-compiled regular expressions

---

core/graph.ml
core/lib.ml

OCaml 4.12 added `List.compare` which conflicts with the use of `compare` in those modules where the `List` module is opened.

Add support for OCaml 4.12

---

core/webif.ml

This fixes #198 by mutating the request data to set http response code to 500 whenever there is an error.

fix to set response to 500 on error

---

core/frontend.ml

Not to be merged, we should have tests exercising `desugarCP` and any interactions with `desugarInners` first.  Would close #773.

WIP: attempt to fix issue 773

---

.travis.yml
links-mysql.opam
links-mysql8.opam
links-postgresql.opam

Required to release `links` and `links-{mysql,postgresql,sqlite3}` (and also `links-mysql8`) simultaneously. C.f. ocaml/opam-repository#18781.

Constrain Links version in links-{mysql,mysql8,postgresql}.opam

---

core/basicsettings.ml
links.opam

Links 0.9.3 has been released. This commit bumps the development version of Links to 0.9.4.

Bump Links version to 0.9.4

---

test-harness

Commit bacc5e2e930ab7453f6d7ea6bcac48457e3e22c8 introduced a bug into `test-harness` that made all .tests files with a header containing a config file fail silently.
This PR fixes the concrete bug causing the exception in `test-harness` and adds logic for detecting such exceptions in the future (instead of the ignoring them and considering the test as passed).

Fix test-harness silently failing when config file provided in header

---

core/commonTypes.ml
core/desugarFormlets.ml
core/desugarPages.ml
core/desugarProcesses.ml
core/irCheck.ml
core/lib.ml
core/sugarConstructors.ml
core/typeSugar.ml
core/typeUtils.ml
core/typeUtils.mli
core/types.ml
core/types.mli

Consolidate primitive row labels and type information.
This patch removes every handcrafted row with wild and hear labels in
favour of using a more structured approach based on a set of new
primitives for working with rows and labels. Specifically, this patch
extends the interface of `Types` with the following operations.
* `hear`: primitive label hear
* `wild`: primitive label wild
* `hear_present`: constructs a present hear field spec.
* `wild_present`: constructs a present wild field spec.
* `closed_wild_row`: a closed row with the primitive wild label present.
* `open_row`: opens a closed row.
* `close_row`: closes an open row.
* `remove_field`: removes a field from a row.

Consolidate primitive row labels and type information

---

core/desugarFormlets.ml
core/desugarFors.ml
core/typeUtils.ml
core/typeUtils.mli

The function `tt` is duplicated in `desugarFormlets.ml` and `desugarFors.ml`. This patch moves the definition of `tt` to `typeUtils.ml` and renames it to `pack_types`.

Move the function `tt` to typeUtils.ml

---

core/desugarInners.ml
tests/freezeml.tests

In DesugarInners, within a group of recursive functions, calls to such a polymorphic, recursive function `f` are modified to type applications of the form `~f [T1, ... , Tn]`, where the Ti are appropriate type arguments. This is to accommodate the fact that in `TypeSugar`, the functions are not considered polymorphic, yet.
However, the existing logic had a bug where already frozen usages of `f` (i.e., `~f`) were also transformed into type applications.

In DesugarInners, don't patch already frozen variables

---

core/parser.mly
tests/continuations.tests

This patch allows the body of an escape expression to be any syntactic
expression.
Resolves #921.

Permissive escape bodies

---

core/parser.mly
test-harness
tests/parser.tests

This patch adds surface syntax for `Mono` restriction.
This patch also fixes a small subtlety in the `test-harness` script
which would make settings in global config files take precedence over
test-local `args`.
Resolves #987.

Surface syntax for Mono restriction.

---

bin/repl.ml
core/desugarEffects.ml

This patch fixes a couple of bugs w.r.t. to error printing/handling, which would be visible in the REPL, e.g.
```
sig f : () -> T
fun f() { Foo }
links> @load "foo.links";
unknown directive : @load
```
The directive `@load` is uncertainly not unknown. What has happened
here is that the type constructor `T` is unbound, which in
`desugarEffects` would raise `NotFound`, which in turn would propagate
all the way out to the REPL, which catches `NotFound`, however, it
excepts the `NotFound` exception to raised if the given directive is
not found in the association list `directives`.
This patch fixes the exception raising points in `desugarEffects` to
raise `UnboundTyCon` instead, and wraps `@load` in `Errors.display`.

Wrap `@load` in an error handler.

---

core/webif.ml

This patch fixes issue #1011. Patch #947 modified the response code
for error messages to be 500. Every client call aborts its server
process, and when a process aborts it throws the exception `Aborted`,
meaning it would inadvertently set the response code to 500. In the
long term we should probably reconsider the design of processes,
remote calls, etc.

Default HTTP response when process throws `Aborted`.

---

core/irtojs.ml

Literal JSON objects must be passed to the client as string literals,
which are supplied to `JSON.parse` in order to avoid crashing the V8
parser for JavaScript literal JSON objects (it is a recursive descent
parser, which `JSON.parse` apparently isn't).
Technically, we need to do this trick for all literal objects that the
JavaScript compiler produces, including records, lists, and
variants. This patch only does it for top-level let bindings.
Partial fix for #1013. I will merge this patch after #1015.

Coping with deeply nested literal JSON objects.

---

lib/js/jslib.js

This patch fixes #1021. The problem was that the arguments inside call
packages received from the server were unresolved.
A unified approach to handling of values received from the server is
warranted.

Resolve arguments inside call packages.

---

bin/repl.ml

Prior to this patch the REPL would unconditionally print a backtrace
whenever a user would input an unsupported directive. Due to
buffering, the backtrace would only be printed next time the buffers
were flushed, e.g. by quitting the REPL.
```
links> @show abc;
unknown directive : show
(CTRL+D)
Raised at Links_core__Notfound.not_found in file "core/notfound.ml", line 20, characters 4-159
Called from Repl.execute_directive in file "bin/repl.ml", line 258, characters 18-54
```
This patch removes the unconditional backtrace print.

Do not print backtrace on "unknown directive"

---

core/types.ml
tests/roundtrippable_types.tests

Fixes #1024.
The issue was that the original code did not use the already flattened version of the row for printing the row variable in function arrows.
The problem was caused by the internal structure like this (in the particular example from #1024):
```links
fun() { error("") } : () { | {wild:()} }-> _
```
note the nested internal row within the variable of the external row, which reduces to `() {wild:()}-> _` and hence to `() ~> _`.

Fix nested effect rows printing incorrectly

---

core/irtojs.ml
lib/js/jslib.js

This patch converts the function `resolveServerValue` into CPS with a
trampoline such that resolution of deeply nested server values no
longer causes a stack overflow.
Resolves #1013.

Robust resolution of deeply nested server values.

---

core/parser.mly

This commit restores the `[| |p|]` syntax for variants, whilst keeping
the sugar `[|p|]`.

Restore row variable syntax for variants

---

CHANGES.md

Update to CHANGES.md, see #1042. It seems I cannot push it directly without a PR.

Update CHANGES.md with recursive rows, roundtrip printer and effect sugar

---

core/proc.ml
database/mysql-driver/dune
database/mysql8-driver/dune
dune

This commit addresses the warnings emitted by OCaml 4.13. In
particular, I have decided to silence/ignore warning 70, which is
produced whenever a source file does not have a corresponding
interface file. I removed the redundant flags from
`database/{mysql-driver,mysql8-driver}/dune`. They are now inherited
from the profile flags specified in the root `dune` file. OCaml 4.13
also warned about an unused field in `core/proc.ml`, which I have just
silenced by adding an underscore prefix to the field name. In the
future we should probably refactor this particular module.
Resolves #1054.

Address warnings emitted by OCaml 4.13.

---

lib/js/jslib.js

This commit deserialises received messages in the `MESSAGE_DELIVERY`
branch of `jslib.js`. This fixes the problem that the UG students have
run into.
As the comment in the code says, a refactoring of this code is
warranted.

Deserialise messages in `onMessage`.

---

.github/workflows/default.yml

The headless testing infrastructure has turned out to be fragile, and
as agreed on a previous meeting we will disable headless testing until
we have ironed out the issues.

Disable webbrowser workflow.

---

core/query/evalMixingQuery.ml
core/query/mixingQuery.ml
core/query/queryLang.ml
lib/js/jslib.js
tests/database/mixing.links
tests/database/mixing.sql
tests/database/testsuite.json

This PR fixes issue #1067 with queries using deduplication:
The fix consists of three small changes:
- the function `QueryLang.used_database`, which incorrectly ignored deduplicated subexpressions, now performs recursion under deduplication: this corrects the "unoptimized query" problem (which was caused by Links incrrectly determining that deduplicated subexpressions didn't require the database)
- the function `MixingQuery.freshen_for_bindings` was incorrectly throwing away `Q.Prom` and `Q.Dedup` constructors when performing recursion. This was at the basis of the problem that caused certain uses of distinct/dedup to be ineffective and has been fixed
- the function `QueryLang.lookup_fun` does NOT hardcode `distinct` as a `Primitive` operation any more, letting Links unfold it to a …

Fixes #1067

---

CHANGES.md
core/desugarTypeVariables.ml
core/lexer.mll
core/parser.mly
core/sugarConstructors.ml
core/sugarConstructorsIntf.ml
core/typeSugar.ml
core/types.ml
core/types.mli
tests/polymorphism.tests

This PR enables writing expression of the form `/\ [Q]. { E }`, where Q is a list of quantifiers and E is an expression with the quantifiers Q in scope. Assuming that E has type T, the overall type is `forall Q.T`.
For example, we may write
```
/\ [a, e :: Row] { sig f : (a) -e-> a fun f(x) {x} ~f }
```
of type `forall a, e::Row. (a) -e-> a`.
One important restriction to ensure that such /\ expressions have most general types is that the type T of E must be unambiguous/unique.
As an example why this is important, consider the following function:
```
fun outer() {
var inner = /\ [e::Row] { fun f(x) {x + 1} };
~inner
}
```
What should `outer`'s type be? If the inner function uses `e` as its effect variable, we have 
```
outer : forall e::Row. (Int) -e-> (Int)
```
However, if the inner …

Implement System F-style general-purpose type abstractions

---

bin/driver.ml
bin/links.ml
bin/repl.ml
core/PP.ml
core/basicsettings.ml
core/desugarModules.ml
core/errors.ml
core/errors.mli
core/irtojs.ml
core/irtojs.mli
tests/shredding/config.pgsql

This patch makes it possible to run Links in a "compile only mode"
which will store the output of `Irtojs.generate_program` in a
file. Note that the generated file may not be directly runnable
without linking the runtime system first. As of writing, the runtime
system must be linked manually, if required.

Add option to save the output of the JavaScript compiler

---

CHANGES.md
core/query/mixingQuery.ml
tests/database/mixing.links

This is straightforward: the mixing normaliser (`mixingQuery.ml`) has an issue with `For` when its body is a `Concat`: the comprehension would normally be split along concatenation, but this does not happen. 
The issue is caused by the changes made to normalisation to allow it to consider normal forms where comprehension generators can be complex queries: in order for these changes to work, we must add a recursive call to `MixingQuery.reduce_for_body` (which until now was non-recursive).
The old normaliser doesn't show this bug, for reasons not entirely clear (but related to the simpler structure of homogeneous bag normal forms). However it's now advisable that the code responsible for normalising comprehensions should be refactored to make its rationale more understandable (without a …

Fixes #1075

---

core/errors.ml
core/errors.mli
core/page.ml
core/webserver.ml
core/webserver_types.mli
lib/js/jslib.js
links.opam

This patch makes it possible for the built-in webserver to serve
requests via https.
To enable secure connections, you must first obtain an adequate
certificate and key, e.g. via Let's Encrypt or a self-signed
certificate. The latter can be useful for testing, e.g. the following
command starts an interactive process to create a self-signed
certificate (that uses 4096 bits RSA encryption and is valid for 365 days):
```shell
openssl req -x509 -newkey rsa:4096 -keyout server.key -out server.crt -days 365 -nodes
```
After obtaining a valid certificate, you must tell Links to run in SSL
mode and you must also tell it how to locate the `key` and `crt` file. This can be done via a configuration file, e.g.
```
ssl=true
ssl_cert_file=server.crt
ssl_key_file=server.key
```
Then running `./links …

Secure connections

---

examples/mvu/dispatch.links
lib/stdlib/mvu.links
tests/typecheck_examples.tests

This fairly simple patch makes it possible to dispatch an MVU message from outside of the event loop. This is particularly useful, for example, when dealing with a persistent, stateful thread which is receiving messages from a server.
* Introduce type alias `MvuHandle(msg)`
* Introduce variants of the `run` functions: `runHandle`, `runCmdHandle`, `runSimpleHandle` which return an `MvuHandle(msg)` rather than the unit value
* Add `Mvu.dispatch : (msg, MvuHandle(msg)) ~> ()`, which directly dispatches a message to the MVU loop
The patch is structured in such a way that the change is backwards-compatible.
See `examples/mvu/dispatch.links` for an example.

Allow direct dispatch of messages to MVU event loop

---

lib/js/jslib.js

This patch provides a quickfix for #1095 as it delays evaluation of the potentially expensive condition expressions of `_$Debug.assert`. I will look into a preprocessor-based solution to dispense entirely of `_$Debug.debug` and `_$Debug.assert` when we start doing more serious benchmarking.
Resolves #1095.

Delayed assert condition expressions

---

prelude.links

This patch slightly changes the semantics of the function `replicate` in `prelude.links` such that it conforms more closely with the semantics of `replicate` from the Haskell prelude. In particular, `replicate` now returns an empty list on non-positive arguments.
Resolves #1068.

[Prelude] replicate: Return empty list on non-positive argument.

---

core/page.ml
lib/js/jslib.js

This is a minor follow-up patch on #1087. It fixes a couple of additional bugs discovered in the runtime. It also gets rid of all uses of spread syntax, as it is not supported by some of the tools we wish to feed Links applications to. For the same reason this patch also gets rid of all uses of `for (... in ...)` in favour of ordinary `for`-loops.

JavaScript runtime cleanup

---

core/page.ml
examples/games/pacman.links
lib/js/jslib.js

The following browser related warnings/noises have been fixed:
- `The character encoding of a framed document was not declared. The document may appear different if viewed without the document framing it.` (every Links page)
- `Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content.` (every Links page)
- `getNodeById: ID blue0 does not exist` (mandelbrot.links)
- Cookie warnings (wine.links)
- Noise printed by pacman.links in the developer console when running with `debug=false`
Resolves #1020

No more noisy pages

---

bin/driver.ml
core/basicsettings.ml
core/irtojs.ml
core/page.ml
core/utility.ml
core/webserver.ml
core/webserver_types.ml
core/webserver_types.mli
lib/js/jslib.js

This patch is a follow-up on patch #1083. This patch adds two new (experimental) options to Links `-Ljs-runtime` and `-Xcustom-js-runtime`. The former option instructs the Links compiler to statically link the JavaScript runtime into a JavaScript compilation artefact. The latter option lets the user override the default JavaScript runtime (i.e. `jslib.js`) with a runtime of their own choosing.

Options for linking JS runtime

---

core/basicsettings.ml

The `output_file` option was missing a converter, causing it to raise an exception when used.

Fix `output_file` option

---

lib/js/jslib.js

The variable `DEBUGGING` was inadvertently referenced in the body of the `_$Debug` module, where we meant to reference `debugMode`.

Fix JSLIB regression

---

core/lib.ml
examples/mvu/dates.links
lib/js/jslib.js
tests/datetime.tests

Equality was not implemented on the server, and comparisons weren't
correctly implemented on the client.
Fixes #1126

Fix comparison operations for DateTime

---

lib/js/jslib.js

This was a silly one -- `DateTime.getMonth()` is 0-indexed rather than 1-indexed (i.e., January is month 0).
Fixes #1119.

Fix off-by-one errors in month serialisation (Issue #1119)

---

core/evalir.ml
core/json.ml
core/resolveJsonState.ml
core/serialisation.ml
core/value.ml
core/value.mli
core/webif.ml
lib/js/jslib.js

This patch fixes a problem with calling remote server functions that
will call a client side function. Previously, client side closures
were stored in a global table `_closureTable`. Such a closure would
get serialised as an index into this table, however, the server
evaluator is unaware of how to invoke a closure contained within this
table, thus resulting in a 500 Internal Error being thrown.
This patch adds a new value form on the server side `ClientClosure
of int` to represent a client side closure, where the integer payload
is the index into the global closure table. In addition the evaluator
is extended with a clause for `ClientClosure` which produces a
client side call to a special function that knows how to access and
invoke the targetted closure in the global table.
Resolves …

Fix remote calls involving client closures.

---

core/types.ml

The `Lens` type traversal was unimplemented and filled in with an `assert false`. As a result, all RL code fails.
I don't think there is any really sensible default traversal due to the complexity of the Lens types, so I have just filled it in with the identity. This doesn't stop someone implementing a traversal -- they'll just need to write one for `Lens.Type.t` type and plug it in as usual.

Fix assert error with relational lenses

---

run-tests
tests/unit/config.nodb.sample
tests/unit/config.sample

The sample config for the database unit test suite was using hardcoded constants rather than the `$LINKS_POSTGRES_*` family of environment variables like the rest of the testing infrastructure.

Fix database unit test suite sample config

---

prelude.links

The current `Process` type gives the type of effects that a process can perform.
When using actor style concurrency, this will typically be of the form
```Process({hear: Foo})```
for some message of type `Foo`. (I often forget the specific syntax).
Indeed this is a fairly common use case. Especially when writing MVU applications, it's often good practice to write down type signatures for PIDs if they're contained within a model.
This small patch introduces a synonym `Pid(A) = Process({hear: A})` for some type A, so we can just write
```Pid(Foo)```
This won't be flexible enough for some cases where we want the more fine-grained reasoning about the effects performed by the spawned process, but IMO it's an easy win for a majority of cases.

Simpler PID synonym for processes

---

examples/mvu/commands.links
examples/mvu/dispatch.links
examples/mvu/pong.links
examples/mvu/time.links
lib/stdlib/mvuAttrs.links
lib/stdlib/mvuHTML.links

The monoidal units of MvuHTML.HTML and MvuAttrs.Attr are accessed by `MvuHTML.empty` and `MvuAttrs.empty`.
When creating a tree, these are quite verbose to use, so the pattern I've ended up doing is:
```
var a0 = MvuAttrs.empty;
var h0 = MvuHTML.empty;
div(a0, h0)
```
I do this so much that I think it would actually be better to have these shortcuts in the actual libraries. It's handy for me and I don't see any harm in it.

Add h0 and a0 to MvuHTML and MvuAttrs libraries

---

core/irtojs.ml
examples/handlers/js/alert.js
examples/handlers/js/canvas.js
examples/handlers/js/runtime.js
examples/handlers/racing-lines.links
examples/handlers/sierpinski-triangle.links

The refactoring of the JavaScript compiler earlier this year apparently introduced a regression in the compilation of effect handlers. This regression manifests computation pattern matching, where the payload of any matched operation was not properly extracted.
This patch also brings
`examples/handlers/{racing-lines,sierpinski-triangle}.links` up to date with the new JavaScript runtime API, meaning these examples now runs correctly again.

Fix regression in compilation of effect handlers to JavaScript.

---

.github/workflows/default.yml
bin/dune
bin/repl.ml
core/debug.ml
core/dune
core/query/queryLang.ml
database/mysql-driver/dune
database/mysql8-driver/dune
database/pg-driver/dune
database/sqlite3-driver/dune
lens/dune
linkspath/dune

This patch makes our code base compile with OCaml 5.0.0, whilst maintaining compatibility with OCaml 4.08+.
This patch also changes the CI to use OCaml 4.14.1 and OCaml 5.0.0.

Compile with OCaml 5.0.0

---

core/basicsettings.ml
core/compilePatterns.ml
core/desugarSessionExceptions.ml
core/lib.ml
core/typeSugar.ml
lib/stdlib/monitorConnection.links

Session exceptions are compiled into effects and handlers. A practical difficulty with this is that code can become polluted with the `SessionFail` effect. Moreover, if session exceptions are switched on then the typing rules for all of the spawn operators change to take into the `SessionFail` effect (see core/lib.ml). This PR adds an experimental setting `expose_session_fail` which defaults to `true` (giving the old behaviour), but when set to `false` will hide the `SessionFail` effect as part of the built-in `wild` effect.
The PR is technically incomplete as it does not include special cases for treating `SessionFail` in the IR type checker when `expose_session_fail` is disabled, but it is safely hidden behind an experimental setting and is already sufficient to use for practical …

Hide session fail

---

Makefile
linkspath/gen_linkspath.ml

This patch makes the build infrastructure for Links more robust. Previously, the build infrastructure would assume that it is running in an environment populated by OPAM. This assumption is too optimistic; for example a Docker container will give you a blank environment by default. To make it easier to install Links in such environments we now prefix dune build commands with `opam exec`. This command resolves the installation directory of dune and makes sure it is invoked with a suitable environment.
Furthermore, the `gen_linkspath.exe` install helper would only test whether Links is being built by OPAM, and if that was not the case then it would assume Links was being built from sources in a local checkout of the git repository. This assumption is a tad optimistic too. So now, if we …

Robust build infrastructure

---

lens/column.ml
lens/database.ml
lens/sort.ml
lens/value.ml
links.opam

This PR implements a better workaround for #1187.
The previous workaround was to force using an older version of  the `ppx_sexp_conv`, which did not exhibit issue #1187. As such a version constraint may inconvenience users, this PR removes the version constraint and touches the problematic uses of `@@deriving sexp` directly.
Unforutnately, locally suppressing the warning code 40 triggered by the code generated for `@@deriving sexp` is somewhat tricky, as there is no AST node in the original source file to attach an `ocaml.warning` attribute to.
This PR circumvents this problem by wrapping the affected type definitions in an anonymous module, disabling warning 40 within that whole module, and then immediately `include`ing said module.
This limits the scope in which we actually disable …

Better workaround for issue #1187 (warning 40 due to @@deriving sexp)

---

examples/sierpinski_bits.links
tests/typecheck_examples.tests

This is a little fun and silly example program which computes and renders the Sierpinski triangle using bitwise-and.
```links
links> sierpinski();
********************************
* * * * * * * * * * * * * * * *
**  **  **  **  **  **  **  **
*   *   *   *   *   *   *   *
****    ****    ****    ****
* *     * *     * *     * *
**      **      **      **
*       *       *       *
********        ********
* * * *         * * * *
**  **          **  **
*   *           *   *
****            ****
* *             * *
**              **
*               *
****************
* * * * * * * *
**  **  **  **
*   *   *   *
****    ****
* *     * *
**      **
*       *
********
* * * *
**  **
*   *
****
* *
**
*
() : ()
```

A silly example program

---

.github/workflows/default.yml
core/irCheck.ml
dune-project
links.opam
tools/rule-check

This patch bundles #1199, #1204, and #1208 into one.
This patch makes it possible to compile Links with the recently released OCaml 5.3.0 compiler. In OCaml 5.3.0 the token `effect` has become a keyword, and thus cannot be used as the name of a binder anymore.
Github is deprecating the CI image `ubuntu-20.04`:
> The Ubuntu 20.04 runner image will be fully unsupported by April 1, 2025. To raise awareness of the upcoming removal, we will temporarily fail jobs using Ubuntu 20.04. Builds that are scheduled to run during the brownout periods will fail. The brownouts are scheduled for the following dates and times:
>
>    March 4 14:00 UTC – 22:00 UTC
>    March 11 13:00 UTC – 21:00 UTC
>    March 18 13:00 UTC – 21:00 UTC
>    March 25 13:00 UTC – 21:00 UTC
>
> What you need to do
>
> Jobs …

Fix CI failures and restore compatibility with OCaml 5.3

---

dune-project
links.opam

This patch sets the minimum supported version of the OCaml compiler to 5.3.0. OCaml 5.3.0 introduced new syntax for effect handlers, so we need to set this lower bound if we want to take advantage of the syntax and at the same time distribute Links via OPAM.

Raise minimum supported OCaml compiler to 5.3.0

---

core/parser.mly
core/typeSugar.ml

This PR fixes two issues:
- If one kind of unification issue related to effects occurs, the old `links` tries to generate an error message but the content of that error message generates an internal error;
- If linearity is not tracked, `lindo` should be parsed exactly the same as `do` and `case <Foo =@ k>` like `case <Foo => k>`.
MWE:
```
sig f : () {A:() =@ Bool|_}~> Bool
fun f() { lindo A() }
```
This MWE generates the error in the old `links` when it is supposed to be correct.
Note that removing the signature of `f` makes it work regardless of the fix, as the type will be automatically inferred with a linear effect before linearity is dropped.
```
sig f : (s) {A:(s) {}-> () |_}-> ()
fun f(st) {do A(st)}
```
This MWE generates an internal error in the old `links`. The proposed fix …

Effects typechecking fixes
